#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

"$REPO_ROOT/scripts/write_exp04_offset_report_files.sh" --output-root "$TMP_DIR" >/dev/null

test -f "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
test -f "$TMP_DIR/SUMMARY.metta"
test -f "$TMP_DIR/RUN.md"

grep -Fq 'This directory is generated by `scripts/write_exp04_offset_report_files.sh` from' "$TMP_DIR/RUN.md"
grep -Fq 'offset partitions, representative cores, and the scientific claim stay' "$TMP_DIR/RUN.md"
grep -Fq '`exp04-offset-sensitivity-20260709` from `(exp04-offset-sensitivity-report-bundle)`' "$TMP_DIR/RUN.md"

grep -Fq '(offset-sensitivity-row hand-designed basal-4 offsets-tested (1 2 3 4 5 6 7 8 9)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq 'raf-negative-offsets (1 2 3 6 7)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq 'raf-like-offsets (4 5 8 9)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq '(offset-sensitivity-row mechanically-generated-template basal-4 offsets-tested (1 2 3 4 5 6 7 8 9)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq 'representative-core shuffled-4 (glCD)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq '(offset-sensitivity-row mechanically-generated-cross-template basal-4 offsets-tested (1 2 3 4 5 6 7 8 9)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq 'representative-core shuffled-3 (xglAC)' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq '(claim exp04-offset-sensitivity' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq 'unbiased-emergence not-supported' "$TMP_DIR/OFFSET_SENSITIVITY_REPORT.metta"
grep -Fq '(exp04-reduction-sweep-20260708 108 (1 2 3 4 5 6 7 8 9))' "$TMP_DIR/SUMMARY.metta"
