#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

"$REPO_ROOT/scripts/write_exp03_productive_cap_files.sh" --output-root "$TMP_DIR" >/dev/null

expected_files=(CONFIG.metta MANIFEST.metta EVENTS.metta ABUNDANCES.metta METRICS.metta ACS.metta ABLATIONS.metta SUMMARY.metta)
expected_runs=(
  exp03-cap5-productive-seed-13-random
  exp03-cap6-rich-seed-11-random
  exp03-cap6-productive-seed-11-random
  exp03-cap6-productive-seed-13-random
  exp03-cap6-productive-seed-17-random
)

for run_id in "${expected_runs[@]}"; do
  for file in "${expected_files[@]}"; do
    test -f "$TMP_DIR/$run_id/$file"
  done
done

actual_count=$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l)
test "$actual_count" -eq "${#expected_runs[@]}"
test -f "$TMP_DIR/RUN.md"
grep -Fq 'This directory is generated by `scripts/write_exp03_productive_cap_files.sh` from' "$TMP_DIR/RUN.md"
grep -Fq 'PeTTa-side `run-file-bundle` atoms. Python only writes queried sections to disk;' "$TMP_DIR/RUN.md"
grep -Fq '`exp03-cap6-productive-seed-11-random` from `(exp03-cap6-productive-file-bundle seed-11 random)`' "$TMP_DIR/RUN.md"
grep -Fq '`exp03-cap6-productive-seed-13-random` from `(exp03-cap6-productive-file-bundle seed-13 random-polymer)`' "$TMP_DIR/RUN.md"
grep -Fq '`exp03-cap6-productive-seed-17-random` from `(exp03-cap6-productive-file-bundle seed-17 random-polymer)`' "$TMP_DIR/RUN.md"

grep -Fq '(run-config exp03-cap5-productive-seed-13-random exp03 (seed-13) 10 (candidate-cap 5 1) random-polymer)' \
  "$TMP_DIR/exp03-cap5-productive-seed-13-random/CONFIG.metta"
grep -Fq '(metric dynamic-event-count exp03-cap5-productive-seed-13-random 10)' \
  "$TMP_DIR/exp03-cap5-productive-seed-13-random/METRICS.metta"
grep -Fq '(run-summary exp03-cap6-rich-seed-11-random passed cap6-rich-seed-11-six-candidate-dynamics true)' \
  "$TMP_DIR/exp03-cap6-rich-seed-11-random/SUMMARY.metta"
grep -Fq '(event 0 rr5 Q1 Q6 Q16 Q3)' \
  "$TMP_DIR/exp03-cap6-productive-seed-11-random/EVENTS.metta"
grep -Fq '(metric dynamic-event-count exp03-cap6-productive-seed-11-random 12)' \
  "$TMP_DIR/exp03-cap6-productive-seed-11-random/METRICS.metta"
grep -Fq '(run-summary exp03-cap6-productive-seed-11-random passed cap6-productive-sixth-candidate-seed-11 true)' \
  "$TMP_DIR/exp03-cap6-productive-seed-11-random/SUMMARY.metta"
grep -Fq '(run-config exp03-cap6-productive-seed-13-random exp03 (seed-13) 12 (candidate-cap 6 1) random-polymer)' \
  "$TMP_DIR/exp03-cap6-productive-seed-13-random/CONFIG.metta"
grep -Fq '(event 4 rr5 R0 R5 R05 R3)' \
  "$TMP_DIR/exp03-cap6-productive-seed-13-random/EVENTS.metta"
grep -Fq '(metric dynamic-event-count exp03-cap6-productive-seed-13-random 12)' \
  "$TMP_DIR/exp03-cap6-productive-seed-13-random/METRICS.metta"
grep -Fq '(run-summary exp03-cap6-productive-seed-13-random passed cap6-productive-sixth-candidate-seed-13 true)' \
  "$TMP_DIR/exp03-cap6-productive-seed-13-random/SUMMARY.metta"
grep -Fq '(run-config exp03-cap6-productive-seed-17-random exp03 (seed-17) 12 (candidate-cap 6 1) random-polymer)' \
  "$TMP_DIR/exp03-cap6-productive-seed-17-random/CONFIG.metta"
grep -Fq '(event 0 rr5 S0 S5 S05 S3)' \
  "$TMP_DIR/exp03-cap6-productive-seed-17-random/EVENTS.metta"
grep -Fq '(metric dynamic-event-count exp03-cap6-productive-seed-17-random 12)' \
  "$TMP_DIR/exp03-cap6-productive-seed-17-random/METRICS.metta"
grep -Fq '(run-summary exp03-cap6-productive-seed-17-random passed cap6-productive-sixth-candidate-seed-17 true)' \
  "$TMP_DIR/exp03-cap6-productive-seed-17-random/SUMMARY.metta"
