#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

"$REPO_ROOT/scripts/write_exp02_cycle_report_files.sh" --output-root "$TMP_DIR" >/dev/null

test -f "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
test -f "$TMP_DIR/SUMMARY.metta"
test -f "$TMP_DIR/RUN.md"

grep -Fq 'This directory is generated by `scripts/write_exp02_cycle_report_files.sh` from' "$TMP_DIR/RUN.md"
grep -Fq 'cycle scanning, folded totals, and report completeness remain in PeTTa.' "$TMP_DIR/RUN.md"
grep -Fq '`exp02-cycle-scan-summary-report` from `(exp02-cycle-scan-report-bundle)`' "$TMP_DIR/RUN.md"

grep -Fq '(cycle-scan-summary-row 4 generated-unplanted-control 40 120 0)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(cycle-scan-summary-row 5 generated-unplanted-control 40 120 0)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(cycle-scan-summary-row 6 generated-unplanted-control 40 120 0)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(cycle-scan-summary-row 7 generated-unplanted-control 40 120 0)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(cycle-scan-summary-note scanners-validated-by-planted-cycle-fixtures)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(cycle-scan-summary-note no-generated-unplanted-k4-through-k7-cycles)' "$TMP_DIR/CYCLE_SCAN_REPORT.metta"
grep -Fq '(exp02-cycle-scan-report generated-unplanted-control cycle-sizes-4-through-7' "$TMP_DIR/SUMMARY.metta"
grep -Fq '(complete? true)' "$TMP_DIR/SUMMARY.metta"
