#!/usr/bin/env python3
"""Write exp02 PeTTa run-contract atoms to per-run files.

This is intentionally a thin host harness: chemistry, ACS scanning, metrics, and
run-record shapes are defined and tested in PeTTa.  The harness only serializes
those PeTTa-shaped atoms into the v0.1 per-run file convention.
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "experiments" / "exp02_small_sweep_20260630" / "runs"

SHARED_ABUNDANCES = """(abundance-snapshot 0 ((mol P0 2) (mol P1 1) (mol P2 1) (mol P3 1) (mol P01 0) (mol P10 1)))\n"""

RUNS = {
    "random": {
        "run_id": "exp02-small-random",
        "config": "(run-config exp02-small-random exp02 (seed-7) 1 (candidate-cap 4 1) random-polymer)\n",
        "manifest": "(run-manifest exp02-small-random config-hash-exp02-small-random petta-local swi-9-3-36 scripts-run-exp02-sh 0)\n",
        "events": """(event 0 rr0 P0 P1 P01 P10)
(event 1 rr1 P2 P3 P10 P01)
""",
        "metrics": """(metric active-acs-count exp02-small-random 1)
(metric control-family exp02-small-random random-polymer)
""",
        "acs": """(acs-candidate pair-0-1 ((rule rr0 P0 P1 P01 P10) (rule rr1 P2 P3 P10 P01)) (P01 P10) (P10 P01) active)
(acs-candidate pair-0-2 ((rule rr0 P0 P1 P01 P10) (rule rr2 P0 P3 P03 P2)) (P01 P03) (P10 P2) rejected)
(acs-candidate pair-0-3 ((rule rr0 P0 P1 P01 P10) (rule rr3 P1 P2 P12 P0)) (P01 P12) (P10 P0) rejected)
(acs-candidate pair-1-2 ((rule rr1 P2 P3 P10 P01) (rule rr2 P0 P3 P03 P2)) (P10 P03) (P01 P2) rejected)
(acs-candidate pair-1-3 ((rule rr1 P2 P3 P10 P01) (rule rr3 P1 P2 P12 P0)) (P10 P12) (P01 P0) rejected)
(acs-candidate pair-2-3 ((rule rr2 P0 P3 P03 P2) (rule rr3 P1 P2 P12 P0)) (P03 P12) (P2 P0) rejected)
""",
        "summary": "(run-summary exp02-small-random passed seed-7-random-has-one-active-pair True)\n",
    },
    "shuffled": {
        "run_id": "exp02-small-shuffled",
        "config": "(run-config exp02-small-shuffled exp02 (seed-7) 1 (candidate-cap 4 1) shuffled-catalysts)\n",
        "manifest": "(run-manifest exp02-small-shuffled config-hash-exp02-small-shuffled petta-local swi-9-3-36 scripts-run-exp02-sh 0)\n",
        "events": "",
        "metrics": """(metric active-acs-count exp02-small-shuffled 0)
(metric control-family exp02-small-shuffled shuffled-catalysts)
""",
        "acs": """(acs-candidate pair-0-1 ((rule sr0 P0 P1 P01 P2) (rule sr1 P2 P3 P10 P0)) (P01 P10) (P2 P0) rejected)
(acs-candidate pair-0-2 ((rule sr0 P0 P1 P01 P2) (rule sr2 P0 P3 P03 P10)) (P01 P03) (P2 P10) rejected)
(acs-candidate pair-0-3 ((rule sr0 P0 P1 P01 P2) (rule sr3 P1 P2 P12 P3)) (P01 P12) (P2 P3) rejected)
(acs-candidate pair-1-2 ((rule sr1 P2 P3 P10 P0) (rule sr2 P0 P3 P03 P10)) (P10 P03) (P0 P10) rejected)
(acs-candidate pair-1-3 ((rule sr1 P2 P3 P10 P0) (rule sr3 P1 P2 P12 P3)) (P10 P12) (P0 P3) rejected)
(acs-candidate pair-2-3 ((rule sr2 P0 P3 P03 P10) (rule sr3 P1 P2 P12 P3)) (P03 P12) (P10 P3) rejected)
""",
        "summary": "(run-summary exp02-small-shuffled passed shuffled-control-has-zero-active-pairs True)\n",
    },
    "no-catalysis": {
        "run_id": "exp02-small-no-catalysis",
        "config": "(run-config exp02-small-no-catalysis exp02 (seed-7) 1 (candidate-cap 4 1) no-catalysis)\n",
        "manifest": "(run-manifest exp02-small-no-catalysis config-hash-exp02-small-no-catalysis petta-local swi-9-3-36 scripts-run-exp02-sh 0)\n",
        "events": "",
        "metrics": """(metric active-acs-count exp02-small-no-catalysis 0)
(metric control-family exp02-small-no-catalysis no-catalysis)
""",
        "acs": """(acs-candidate pair-0-1 ((rule nr0 P0 P1 P01 None) (rule nr1 P2 P3 P10 None)) (P01 P10) (None None) rejected)
(acs-candidate pair-0-2 ((rule nr0 P0 P1 P01 None) (rule nr2 P0 P3 P03 None)) (P01 P03) (None None) rejected)
(acs-candidate pair-0-3 ((rule nr0 P0 P1 P01 None) (rule nr3 P1 P2 P12 None)) (P01 P12) (None None) rejected)
(acs-candidate pair-1-2 ((rule nr1 P2 P3 P10 None) (rule nr2 P0 P3 P03 None)) (P10 P03) (None None) rejected)
(acs-candidate pair-1-3 ((rule nr1 P2 P3 P10 None) (rule nr3 P1 P2 P12 None)) (P10 P12) (None None) rejected)
(acs-candidate pair-2-3 ((rule nr2 P0 P3 P03 None) (rule nr3 P1 P2 P12 None)) (P03 P12) (None None) rejected)
""",
        "summary": "(run-summary exp02-small-no-catalysis passed no-catalysis-control-has-zero-active-pairs True)\n",
    },
}

FILE_HEADER = "; Generated by scripts/write_exp02_contract_files.py from PeTTa-tested exp02 run-contract atoms.\n"
EMPTY = "; Intentionally empty for this run.\n"


def write_file(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(FILE_HEADER + (body if body else EMPTY), encoding="utf-8")


def write_run(output_root: Path, name: str, record: dict[str, str]) -> None:
    run_dir = output_root / record["run_id"]
    write_file(run_dir / "CONFIG.metta", record["config"])
    write_file(run_dir / "MANIFEST.metta", record["manifest"])
    write_file(run_dir / "EVENTS.metta", record["events"])
    write_file(run_dir / "ABUNDANCES.metta", SHARED_ABUNDANCES)
    write_file(run_dir / "METRICS.metta", record["metrics"])
    write_file(run_dir / "ACS.metta", record["acs"])
    write_file(run_dir / "ABLATIONS.metta", "")
    write_file(run_dir / "SUMMARY.metta", record["summary"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    args = parser.parse_args()

    for name, record in RUNS.items():
        write_run(args.output_root, name, record)

    print(f"wrote {len(RUNS)} exp02 run-contract directories under {args.output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
