#!/usr/bin/env python3
"""Write the compact exp02 cycle-scan report bundle to files.

This is a thin host harness: it asks PeTTa for the already-tested compact
cycle-scan report file bundle and writes the returned report sections to disk.
Cycle scanning, totals, and the completeness predicate remain in PeTTa
(`src/chem_exp02.metta`).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = Path(os.environ.get("WORKSPACE", "/home/openclaw/research-agent"))
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "artifacts" / "exp02_cycle_scan_report"
FILE_HEADER = "; Generated by scripts/write_exp02_cycle_report_files.py from a PeTTa report-file-bundle.\n"
FILE_NAMES = ("CYCLE_SCAN_REPORT.metta", "SUMMARY.metta")
REPORT_EXPR = "(exp02-cycle-scan-report-bundle)"
RUN_MD = """# exp02 cycle-scan report artifacts

This directory is generated by `scripts/write_exp02_cycle_report_files.sh` from
PeTTa-side compact report atoms. Python only writes queried sections to disk;
cycle scanning, folded totals, and report completeness remain in PeTTa.

## Reproduce

```bash
scripts/write_exp02_cycle_report_files.sh
scripts/test_exp02_cycle_report_files.sh
```

## Bundle

- `exp02-cycle-scan-summary-report` from `(exp02-cycle-scan-report-bundle)`; files: CYCLE_SCAN_REPORT.metta, SUMMARY.metta.
"""
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--petta-runner", type=Path, default=Path(os.environ.get("PETTA_RUNNER", WORKSPACE / "projects" / "omegaclaw" / "repos" / "PeTTa" / "run.sh")))
    parser.add_argument("--swipl-prefix", type=Path, default=Path(os.environ.get("SWI_PREFIX", WORKSPACE / "projects" / "omegaclaw" / "local" / "swipl-9.3.36")))
    parser.add_argument("--no-run-md", action="store_true", help="do not write the compact artifact RUN.md provenance file")
    return parser.parse_args()


def strip_ansi(text: str) -> str:
    return ANSI_RE.sub("", text)


def atom_from_run_file(line: str, expected_file: str) -> str:
    prefix = f"(run-file {expected_file} "
    if not line.startswith(prefix) or not line.endswith(")"):
        raise ValueError(f"expected {prefix!r} wrapper, got: {line}")
    return line[len(prefix):-1]


def query_report_bundle(runner: Path, swipl_prefix: Path) -> dict[str, str]:
    query_lines = [
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp01.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'run_contract.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp02.metta'})",
        f"!(report-file-bundle-id {REPORT_EXPR})",
        f"!(report-file-bundle-report-file {REPORT_EXPR})",
        f"!(report-file-bundle-summary-file {REPORT_EXPR})",
    ]
    with tempfile.NamedTemporaryFile("w", suffix=".metta", delete=False) as handle:
        handle.write("\n".join(query_lines) + "\n")
        query_path = Path(handle.name)

    env = os.environ.copy()
    env["PATH"] = f"{swipl_prefix / 'bin'}:{env.get('PATH', '')}"
    env["SWI_HOME_DIR"] = str(swipl_prefix / "lib" / "swipl")
    lib_path = swipl_prefix / "lib" / "swipl" / "lib" / "x86_64-linux"
    env["LD_LIBRARY_PATH"] = f"{lib_path}:{env.get('LD_LIBRARY_PATH', '')}"

    try:
        completed = subprocess.run(
            ["sh", str(runner), str(query_path)],
            cwd=REPO_ROOT,
            env=env,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    finally:
        query_path.unlink(missing_ok=True)

    lines = [line.strip() for line in strip_ansi(completed.stdout).splitlines() if line.strip()]
    results = lines[-(1 + len(FILE_NAMES)):]
    if results[0] != "exp02-cycle-scan-summary-report":
        raise ValueError(f"bundle id mismatch: expected exp02-cycle-scan-summary-report, got {results[0]}")
    return {filename: atom_from_run_file(line, filename) for filename, line in zip(FILE_NAMES, results[1:])}


def main() -> None:
    args = parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)
    sections = query_report_bundle(args.petta_runner, args.swipl_prefix)
    for filename in FILE_NAMES:
        (args.output_root / filename).write_text(f"{FILE_HEADER}{sections[filename]}\n", encoding="utf-8")
    if not args.no_run_md:
        (args.output_root / "RUN.md").write_text(RUN_MD, encoding="utf-8")
    print(f"wrote exp02 cycle-scan report bundle to {args.output_root}")


if __name__ == "__main__":
    main()
