#!/usr/bin/env python3
"""Write exp02 PeTTa run-contract atoms to per-run files.

This is intentionally a thin host harness: chemistry, ACS scanning, metrics, and
run-record shapes are defined and tested in PeTTa.  The harness serializes the
PeTTa-tested sweep points into the v0.1 per-run file convention; the active-pair
labels below mirror exp02 smoke-test expectations rather than driving chemistry.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "experiments" / "exp02_small_sweep_20260630" / "runs"

FILE_HEADER = "; Generated by scripts/write_exp02_contract_files.py from PeTTa-tested exp02 run-contract atoms.\n"
EMPTY = "; Intentionally empty for this run.\n"

ABUNDANCES_BY_SEED = {
    "seed-7": "(abundance-snapshot 0 ((mol P0 2) (mol P1 1) (mol P2 1) (mol P3 1) (mol P01 0) (mol P10 1)))\n",
    "seed-11": "(abundance-snapshot 0 ((mol Q0 2) (mol Q1 1) (mol Q2 1) (mol Q3 1) (mol Q01 0) (mol Q10 1)))\n",
    "seed-13": "(abundance-snapshot 0 ((mol R0 2) (mol R1 1) (mol R2 1) (mol R3 1) (mol R01 0) (mol R10 1)))\n",
    "seed-17": "(abundance-snapshot 0 ((mol S0 2) (mol S1 1) (mol S2 1) (mol S3 1) (mol S01 0) (mol S10 1)))\n",
    "seed-19": "(abundance-snapshot 0 ((mol T0 2) (mol T1 1) (mol T2 1) (mol T3 1) (mol T01 0) (mol T23 0)))\n",
    "seed-23": "(abundance-snapshot 0 ((mol U0 2) (mol U1 1) (mol U2 1) (mol U3 1) (mol U01 0) (mol U23 0)))\n",
    "seed-29": "(abundance-snapshot 0 ((mol V0 2) (mol V1 1) (mol V2 1) (mol V3 1) (mol V01 0) (mol V23 0)))\n",
    "seed-31": "(abundance-snapshot 0 ((mol W0 2) (mol W1 1) (mol W2 1) (mol W3 1) (mol W01 0) (mol W23 0)))\n",
    "seed-37": "(abundance-snapshot 0 ((mol X0 2) (mol X1 1) (mol X2 1) (mol X3 1) (mol X01 0) (mol X23 0)))\n",
    "seed-41": "(abundance-snapshot 0 ((mol Y0 2) (mol Y1 1) (mol Y2 1) (mol Y3 1) (mol Y01 0) (mol Y23 0)))\n",
    "seed-43": "(abundance-snapshot 0 ((mol Z0 2) (mol Z1 1) (mol Z2 1) (mol Z3 1) (mol Z01 0) (mol Z23 0)))\n",
    "seed-47": "(abundance-snapshot 0 ((mol ZA0 2) (mol ZA1 1) (mol ZA2 1) (mol ZA3 1) (mol ZA01 0) (mol ZA23 0)))\n",
    "seed-53": "(abundance-snapshot 0 ((mol ZB0 2) (mol ZB1 1) (mol ZB2 1) (mol ZB3 1) (mol ZB01 0) (mol ZB23 0)))\n",
    "seed-59": "(abundance-snapshot 0 ((mol ZC0 2) (mol ZC1 1) (mol ZC2 1) (mol ZC3 1) (mol ZC01 0) (mol ZC23 0)))\n",
    "seed-61": "(abundance-snapshot 0 ((mol ZD0 2) (mol ZD1 1) (mol ZD2 1) (mol ZD3 1) (mol ZD01 0) (mol ZD23 0)))\n",
    "seed-67": "(abundance-snapshot 0 ((mol ZE0 2) (mol ZE1 1) (mol ZE2 1) (mol ZE3 1) (mol ZE01 0) (mol ZE23 0)))\n",
    "seed-71": "(abundance-snapshot 0 ((mol ZF0 2) (mol ZF1 1) (mol ZF2 1) (mol ZF3 1) (mol ZF01 0) (mol ZF23 0)))\n",
    "seed-73": "(abundance-snapshot 0 ((mol ZG0 2) (mol ZG1 1) (mol ZG2 1) (mol ZG3 1) (mol ZG01 0) (mol ZG23 0)))\n",
    "seed-79": "(abundance-snapshot 0 ((mol ZH0 2) (mol ZH1 1) (mol ZH2 1) (mol ZH3 1) (mol ZH01 0) (mol ZH23 0)))\n",
}

RULES = {
    ("seed-7", "random-polymer"): [
        ("rr0", "P0", "P1", "P01", "P10"),
        ("rr1", "P2", "P3", "P10", "P01"),
        ("rr2", "P0", "P3", "P03", "P2"),
        ("rr3", "P1", "P2", "P12", "P0"),
    ],
    ("seed-7", "shuffled-catalysts"): [
        ("sr0", "P0", "P1", "P01", "P2"),
        ("sr1", "P2", "P3", "P10", "P0"),
        ("sr2", "P0", "P3", "P03", "P10"),
        ("sr3", "P1", "P2", "P12", "P3"),
    ],
    ("seed-7", "no-catalysis"): [
        ("nr0", "P0", "P1", "P01", "None"),
        ("nr1", "P2", "P3", "P10", "None"),
        ("nr2", "P0", "P3", "P03", "None"),
        ("nr3", "P1", "P2", "P12", "None"),
    ],
    ("seed-11", "random-polymer"): [
        ("rr0", "Q0", "Q1", "Q01", "Q10"),
        ("rr1", "Q2", "Q3", "Q10", "Q01"),
        ("rr2", "Q4", "Q5", "Q45", "Q54"),
        ("rr3", "Q6", "Q7", "Q54", "Q45"),
        ("rr4", "Q0", "Q5", "Q05", "Q2"),
        ("rr5", "Q1", "Q6", "Q16", "Q3"),
    ],
    ("seed-11", "shuffled-catalysts"): [
        ("sr0", "Q0", "Q1", "Q01", "Q2"),
        ("sr1", "Q2", "Q3", "Q10", "Q4"),
        ("sr2", "Q4", "Q5", "Q45", "Q6"),
        ("sr3", "Q6", "Q7", "Q54", "Q0"),
        ("sr4", "Q0", "Q5", "Q05", "Q10"),
        ("sr5", "Q1", "Q6", "Q16", "Q54"),
    ],
    ("seed-11", "no-catalysis"): [
        ("nr0", "Q0", "Q1", "Q01", "None"),
        ("nr1", "Q2", "Q3", "Q10", "None"),
        ("nr2", "Q4", "Q5", "Q45", "None"),
        ("nr3", "Q6", "Q7", "Q54", "None"),
        ("nr4", "Q0", "Q5", "Q05", "None"),
        ("nr5", "Q1", "Q6", "Q16", "None"),
    ],
    ("seed-13", "random-polymer"): [
        ("rr0", "R0", "R1", "R01", "R10"),
        ("rr1", "R2", "R3", "R10", "R01"),
        ("rr2", "R4", "R5", "R45", "R54"),
        ("rr3", "R6", "R7", "R54", "R45"),
        ("rr4", "R8", "R9", "R89", "R2"),
        ("rr5", "R0", "R5", "R05", "R3"),
        ("rr6", "R1", "R6", "R16", "R5"),
        ("rr7", "R2", "R7", "R27", "R9"),
    ],
    ("seed-13", "shuffled-catalysts"): [
        ("rr0", "R0", "R1", "R01", "R2"),
        ("rr1", "R2", "R3", "R10", "R4"),
        ("rr2", "R4", "R5", "R45", "R6"),
        ("rr3", "R6", "R7", "R54", "R8"),
        ("rr4", "R8", "R9", "R89", "R10"),
        ("rr5", "R0", "R5", "R05", "R01"),
        ("rr6", "R1", "R6", "R16", "R45"),
        ("rr7", "R2", "R7", "R27", "R54"),
    ],
    ("seed-13", "no-catalysis"): [
        ("rr0", "R0", "R1", "R01", "None"),
        ("rr1", "R2", "R3", "R10", "None"),
        ("rr2", "R4", "R5", "R45", "None"),
        ("rr3", "R6", "R7", "R54", "None"),
        ("rr4", "R8", "R9", "R89", "None"),
        ("rr5", "R0", "R5", "R05", "None"),
        ("rr6", "R1", "R6", "R16", "None"),
        ("rr7", "R2", "R7", "R27", "None"),
    ],
    ("seed-17", "random-polymer"): [
        ("rr0", "S0", "S1", "S01", "S10"),
        ("rr1", "S2", "S3", "S10", "S01"),
        ("rr2", "S4", "S5", "S45", "S54"),
        ("rr3", "S6", "S7", "S54", "S45"),
        ("rr4", "S8", "S9", "S89", "S2"),
        ("rr5", "S0", "S5", "S05", "S3"),
        ("rr6", "S1", "S6", "S16", "S5"),
        ("rr7", "S2", "S7", "S27", "S9"),
    ],
    ("seed-17", "shuffled-catalysts"): [
        ("rr0", "S0", "S1", "S01", "S2"),
        ("rr1", "S2", "S3", "S10", "S4"),
        ("rr2", "S4", "S5", "S45", "S6"),
        ("rr3", "S6", "S7", "S54", "S8"),
        ("rr4", "S8", "S9", "S89", "S10"),
        ("rr5", "S0", "S5", "S05", "S01"),
        ("rr6", "S1", "S6", "S16", "S45"),
        ("rr7", "S2", "S7", "S27", "S54"),
    ],
    ("seed-17", "no-catalysis"): [
        ("rr0", "S0", "S1", "S01", "None"),
        ("rr1", "S2", "S3", "S10", "None"),
        ("rr2", "S4", "S5", "S45", "None"),
        ("rr3", "S6", "S7", "S54", "None"),
        ("rr4", "S8", "S9", "S89", "None"),
        ("rr5", "S0", "S5", "S05", "None"),
        ("rr6", "S1", "S6", "S16", "None"),
        ("rr7", "S2", "S7", "S27", "None"),
    ],
    ("seed-19", "random-polymer"): [
        ("rr0", "T0", "T1", "T01", "T2"),
        ("rr1", "T2", "T3", "T23", "T4"),
        ("rr2", "T4", "T5", "T45", "T6"),
        ("rr3", "T6", "T7", "T67", "T8"),
        ("rr4", "T8", "T9", "T89", "T0"),
        ("rr5", "T1", "T4", "T14", "T3"),
        ("rr6", "T3", "T6", "T36", "T5"),
        ("rr7", "T5", "T8", "T58", "T7"),
    ],
    ("seed-19", "shuffled-catalysts"): [
        ("rr0", "T0", "T1", "T01", "T3"),
        ("rr1", "T2", "T3", "T23", "T5"),
        ("rr2", "T4", "T5", "T45", "T7"),
        ("rr3", "T6", "T7", "T67", "T9"),
        ("rr4", "T8", "T9", "T89", "T1"),
        ("rr5", "T1", "T4", "T14", "T6"),
        ("rr6", "T3", "T6", "T36", "T8"),
        ("rr7", "T5", "T8", "T58", "T0"),
    ],
    ("seed-19", "no-catalysis"): [
        ("rr0", "T0", "T1", "T01", "None"),
        ("rr1", "T2", "T3", "T23", "None"),
        ("rr2", "T4", "T5", "T45", "None"),
        ("rr3", "T6", "T7", "T67", "None"),
        ("rr4", "T8", "T9", "T89", "None"),
        ("rr5", "T1", "T4", "T14", "None"),
        ("rr6", "T3", "T6", "T36", "None"),
        ("rr7", "T5", "T8", "T58", "None"),
    ],
    ("seed-23", "random-polymer"): [
        ("rr0", "U0", "U1", "U01", "U4"),
        ("rr1", "U2", "U3", "U23", "U6"),
        ("rr2", "U4", "U5", "U45", "U8"),
        ("rr3", "U6", "U7", "U67", "U0"),
        ("rr4", "U8", "U9", "U89", "U2"),
        ("rr5", "U1", "U4", "U14", "U5"),
        ("rr6", "U3", "U6", "U36", "U7"),
        ("rr7", "U5", "U8", "U58", "U9"),
    ],
    ("seed-23", "shuffled-catalysts"): [
        ("rr0", "U0", "U1", "U01", "U5"),
        ("rr1", "U2", "U3", "U23", "U7"),
        ("rr2", "U4", "U5", "U45", "U9"),
        ("rr3", "U6", "U7", "U67", "U1"),
        ("rr4", "U8", "U9", "U89", "U3"),
        ("rr5", "U1", "U4", "U14", "U6"),
        ("rr6", "U3", "U6", "U36", "U8"),
        ("rr7", "U5", "U8", "U58", "U0"),
    ],
    ("seed-23", "no-catalysis"): [
        ("rr0", "U0", "U1", "U01", "None"),
        ("rr1", "U2", "U3", "U23", "None"),
        ("rr2", "U4", "U5", "U45", "None"),
        ("rr3", "U6", "U7", "U67", "None"),
        ("rr4", "U8", "U9", "U89", "None"),
        ("rr5", "U1", "U4", "U14", "None"),
        ("rr6", "U3", "U6", "U36", "None"),
        ("rr7", "U5", "U8", "U58", "None"),
    ],

    ("seed-29", "random-polymer"): [
        ("rr0", "V0", "V1", "V01", "V6"),
        ("rr1", "V2", "V3", "V23", "V8"),
        ("rr2", "V4", "V5", "V45", "V0"),
        ("rr3", "V6", "V7", "V67", "V2"),
        ("rr4", "V8", "V9", "V89", "V4"),
        ("rr5", "V1", "V4", "V14", "V7"),
        ("rr6", "V3", "V6", "V36", "V9"),
        ("rr7", "V5", "V8", "V58", "V1"),
    ],
    ("seed-29", "shuffled-catalysts"): [
        ("rr0", "V0", "V1", "V01", "V7"),
        ("rr1", "V2", "V3", "V23", "V9"),
        ("rr2", "V4", "V5", "V45", "V1"),
        ("rr3", "V6", "V7", "V67", "V3"),
        ("rr4", "V8", "V9", "V89", "V5"),
        ("rr5", "V1", "V4", "V14", "V8"),
        ("rr6", "V3", "V6", "V36", "V0"),
        ("rr7", "V5", "V8", "V58", "V2"),
    ],
    ("seed-29", "no-catalysis"): [
        ("rr0", "V0", "V1", "V01", "None"),
        ("rr1", "V2", "V3", "V23", "None"),
        ("rr2", "V4", "V5", "V45", "None"),
        ("rr3", "V6", "V7", "V67", "None"),
        ("rr4", "V8", "V9", "V89", "None"),
        ("rr5", "V1", "V4", "V14", "None"),
        ("rr6", "V3", "V6", "V36", "None"),
        ("rr7", "V5", "V8", "V58", "None"),
    ],


    ("seed-31", "random-polymer"): [
        ("rr0", "W0", "W1", "W01", "W6"),
        ("rr1", "W2", "W3", "W23", "W8"),
        ("rr2", "W4", "W5", "W45", "W0"),
        ("rr3", "W6", "W7", "W67", "W2"),
        ("rr4", "W8", "W9", "W89", "W4"),
        ("rr5", "W1", "W4", "W14", "W7"),
        ("rr6", "W3", "W6", "W36", "W9"),
        ("rr7", "W5", "W8", "W58", "W1"),
    ],
    ("seed-31", "shuffled-catalysts"): [
        ("rr0", "W0", "W1", "W01", "W7"),
        ("rr1", "W2", "W3", "W23", "W9"),
        ("rr2", "W4", "W5", "W45", "W1"),
        ("rr3", "W6", "W7", "W67", "W3"),
        ("rr4", "W8", "W9", "W89", "W5"),
        ("rr5", "W1", "W4", "W14", "W8"),
        ("rr6", "W3", "W6", "W36", "W0"),
        ("rr7", "W5", "W8", "W58", "W2"),
    ],
    ("seed-31", "no-catalysis"): [
        ("rr0", "W0", "W1", "W01", "None"),
        ("rr1", "W2", "W3", "W23", "None"),
        ("rr2", "W4", "W5", "W45", "None"),
        ("rr3", "W6", "W7", "W67", "None"),
        ("rr4", "W8", "W9", "W89", "None"),
        ("rr5", "W1", "W4", "W14", "None"),
        ("rr6", "W3", "W6", "W36", "None"),
        ("rr7", "W5", "W8", "W58", "None"),
    ],

    ("seed-37", "random-polymer"): [
        ("rr0", "X0", "X1", "X01", "X6"),
        ("rr1", "X2", "X3", "X23", "X8"),
        ("rr2", "X4", "X5", "X45", "X0"),
        ("rr3", "X6", "X7", "X67", "X2"),
        ("rr4", "X8", "X9", "X89", "X4"),
        ("rr5", "X1", "X4", "X14", "X7"),
        ("rr6", "X3", "X6", "X36", "X9"),
        ("rr7", "X5", "X8", "X58", "X1"),
    ],
    ("seed-37", "shuffled-catalysts"): [
        ("rr0", "X0", "X1", "X01", "X7"),
        ("rr1", "X2", "X3", "X23", "X9"),
        ("rr2", "X4", "X5", "X45", "X1"),
        ("rr3", "X6", "X7", "X67", "X3"),
        ("rr4", "X8", "X9", "X89", "X5"),
        ("rr5", "X1", "X4", "X14", "X8"),
        ("rr6", "X3", "X6", "X36", "X0"),
        ("rr7", "X5", "X8", "X58", "X2"),
    ],
    ("seed-37", "no-catalysis"): [
        ("rr0", "X0", "X1", "X01", "None"),
        ("rr1", "X2", "X3", "X23", "None"),
        ("rr2", "X4", "X5", "X45", "None"),
        ("rr3", "X6", "X7", "X67", "None"),
        ("rr4", "X8", "X9", "X89", "None"),
        ("rr5", "X1", "X4", "X14", "None"),
        ("rr6", "X3", "X6", "X36", "None"),
        ("rr7", "X5", "X8", "X58", "None"),
    ],

    ("seed-41", "random-polymer"): [
        ("rr0", "Y0", "Y1", "Y01", "Y6"),
        ("rr1", "Y2", "Y3", "Y23", "Y8"),
        ("rr2", "Y4", "Y5", "Y45", "Y0"),
        ("rr3", "Y6", "Y7", "Y67", "Y2"),
        ("rr4", "Y8", "Y9", "Y89", "Y4"),
        ("rr5", "Y1", "Y4", "Y14", "Y7"),
        ("rr6", "Y3", "Y6", "Y36", "Y9"),
        ("rr7", "Y5", "Y8", "Y58", "Y1"),
    ],
    ("seed-41", "shuffled-catalysts"): [
        ("rr0", "Y0", "Y1", "Y01", "Y7"),
        ("rr1", "Y2", "Y3", "Y23", "Y9"),
        ("rr2", "Y4", "Y5", "Y45", "Y1"),
        ("rr3", "Y6", "Y7", "Y67", "Y3"),
        ("rr4", "Y8", "Y9", "Y89", "Y5"),
        ("rr5", "Y1", "Y4", "Y14", "Y8"),
        ("rr6", "Y3", "Y6", "Y36", "Y0"),
        ("rr7", "Y5", "Y8", "Y58", "Y2"),
    ],
    ("seed-41", "no-catalysis"): [
        ("rr0", "Y0", "Y1", "Y01", "None"),
        ("rr1", "Y2", "Y3", "Y23", "None"),
        ("rr2", "Y4", "Y5", "Y45", "None"),
        ("rr3", "Y6", "Y7", "Y67", "None"),
        ("rr4", "Y8", "Y9", "Y89", "None"),
        ("rr5", "Y1", "Y4", "Y14", "None"),
        ("rr6", "Y3", "Y6", "Y36", "None"),
        ("rr7", "Y5", "Y8", "Y58", "None"),
    ],
    ("seed-43", "random-polymer"): [
        ("rr0", "Z0", "Z1", "Z01", "Z6"),
        ("rr1", "Z2", "Z3", "Z23", "Z8"),
        ("rr2", "Z4", "Z5", "Z45", "Z0"),
        ("rr3", "Z6", "Z7", "Z67", "Z2"),
        ("rr4", "Z8", "Z9", "Z89", "Z4"),
        ("rr5", "Z1", "Z4", "Z14", "Z7"),
        ("rr6", "Z3", "Z6", "Z36", "Z9"),
        ("rr7", "Z5", "Z8", "Z58", "Z1"),
    ],
    ("seed-43", "shuffled-catalysts"): [
        ("rr0", "Z0", "Z1", "Z01", "Z7"),
        ("rr1", "Z2", "Z3", "Z23", "Z9"),
        ("rr2", "Z4", "Z5", "Z45", "Z1"),
        ("rr3", "Z6", "Z7", "Z67", "Z3"),
        ("rr4", "Z8", "Z9", "Z89", "Z5"),
        ("rr5", "Z1", "Z4", "Z14", "Z8"),
        ("rr6", "Z3", "Z6", "Z36", "Z0"),
        ("rr7", "Z5", "Z8", "Z58", "Z2"),
    ],
    ("seed-43", "no-catalysis"): [
        ("rr0", "Z0", "Z1", "Z01", "None"),
        ("rr1", "Z2", "Z3", "Z23", "None"),
        ("rr2", "Z4", "Z5", "Z45", "None"),
        ("rr3", "Z6", "Z7", "Z67", "None"),
        ("rr4", "Z8", "Z9", "Z89", "None"),
        ("rr5", "Z1", "Z4", "Z14", "None"),
        ("rr6", "Z3", "Z6", "Z36", "None"),
        ("rr7", "Z5", "Z8", "Z58", "None"),
    ],    ("seed-47", "random-polymer"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "ZA6"),
        ("rr1", "ZA2", "ZA3", "ZA23", "ZA8"),
        ("rr2", "ZA4", "ZA5", "ZA45", "ZA0"),
        ("rr3", "ZA6", "ZA7", "ZA67", "ZA2"),
        ("rr4", "ZA8", "ZA9", "ZA89", "ZA4"),
        ("rr5", "ZA1", "ZA4", "ZA14", "ZA7"),
        ("rr6", "ZA3", "ZA6", "ZA36", "ZA9"),
        ("rr7", "ZA5", "ZA8", "ZA58", "ZA1"),
    ],
    ("seed-47", "shuffled-catalysts"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "ZA7"),
        ("rr1", "ZA2", "ZA3", "ZA23", "ZA9"),
        ("rr2", "ZA4", "ZA5", "ZA45", "ZA1"),
        ("rr3", "ZA6", "ZA7", "ZA67", "ZA3"),
        ("rr4", "ZA8", "ZA9", "ZA89", "ZA5"),
        ("rr5", "ZA1", "ZA4", "ZA14", "ZA8"),
        ("rr6", "ZA3", "ZA6", "ZA36", "ZA0"),
        ("rr7", "ZA5", "ZA8", "ZA58", "ZA2"),
    ],
    ("seed-47", "no-catalysis"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "None"),
        ("rr1", "ZA2", "ZA3", "ZA23", "None"),
        ("rr2", "ZA4", "ZA5", "ZA45", "None"),
        ("rr3", "ZA6", "ZA7", "ZA67", "None"),
        ("rr4", "ZA8", "ZA9", "ZA89", "None"),
        ("rr5", "ZA1", "ZA4", "ZA14", "None"),
        ("rr6", "ZA3", "ZA6", "ZA36", "None"),
        ("rr7", "ZA5", "ZA8", "ZA58", "None"),
    ],


    ("seed-53", "random-polymer"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "ZB6"),
        ("rr1", "ZB2", "ZB3", "ZB23", "ZB8"),
        ("rr2", "ZB4", "ZB5", "ZB45", "ZB0"),
        ("rr3", "ZB6", "ZB7", "ZB67", "ZB2"),
        ("rr4", "ZB8", "ZB9", "ZB89", "ZB4"),
        ("rr5", "ZB1", "ZB4", "ZB14", "ZB7"),
        ("rr6", "ZB3", "ZB6", "ZB36", "ZB9"),
        ("rr7", "ZB5", "ZB8", "ZB58", "ZB1"),
    ],
    ("seed-53", "shuffled-catalysts"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "ZB7"),
        ("rr1", "ZB2", "ZB3", "ZB23", "ZB9"),
        ("rr2", "ZB4", "ZB5", "ZB45", "ZB1"),
        ("rr3", "ZB6", "ZB7", "ZB67", "ZB3"),
        ("rr4", "ZB8", "ZB9", "ZB89", "ZB5"),
        ("rr5", "ZB1", "ZB4", "ZB14", "ZB8"),
        ("rr6", "ZB3", "ZB6", "ZB36", "ZB0"),
        ("rr7", "ZB5", "ZB8", "ZB58", "ZB2"),
    ],
    ("seed-53", "no-catalysis"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "None"),
        ("rr1", "ZB2", "ZB3", "ZB23", "None"),
        ("rr2", "ZB4", "ZB5", "ZB45", "None"),
        ("rr3", "ZB6", "ZB7", "ZB67", "None"),
        ("rr4", "ZB8", "ZB9", "ZB89", "None"),
        ("rr5", "ZB1", "ZB4", "ZB14", "None"),
        ("rr6", "ZB3", "ZB6", "ZB36", "None"),
        ("rr7", "ZB5", "ZB8", "ZB58", "None"),
    ],
    ("seed-59", "random-polymer"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "ZC6"),
        ("rr1", "ZC2", "ZC3", "ZC23", "ZC8"),
        ("rr2", "ZC4", "ZC5", "ZC45", "ZC0"),
        ("rr3", "ZC6", "ZC7", "ZC67", "ZC2"),
        ("rr4", "ZC8", "ZC9", "ZC89", "ZC4"),
        ("rr5", "ZC1", "ZC4", "ZC14", "ZC7"),
        ("rr6", "ZC3", "ZC6", "ZC36", "ZC9"),
        ("rr7", "ZC5", "ZC8", "ZC58", "ZC1"),
    ],
    ("seed-59", "shuffled-catalysts"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "ZC7"),
        ("rr1", "ZC2", "ZC3", "ZC23", "ZC9"),
        ("rr2", "ZC4", "ZC5", "ZC45", "ZC1"),
        ("rr3", "ZC6", "ZC7", "ZC67", "ZC3"),
        ("rr4", "ZC8", "ZC9", "ZC89", "ZC5"),
        ("rr5", "ZC1", "ZC4", "ZC14", "ZC8"),
        ("rr6", "ZC3", "ZC6", "ZC36", "ZC0"),
        ("rr7", "ZC5", "ZC8", "ZC58", "ZC2"),
    ],
    ("seed-59", "no-catalysis"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "None"),
        ("rr1", "ZC2", "ZC3", "ZC23", "None"),
        ("rr2", "ZC4", "ZC5", "ZC45", "None"),
        ("rr3", "ZC6", "ZC7", "ZC67", "None"),
        ("rr4", "ZC8", "ZC9", "ZC89", "None"),
        ("rr5", "ZC1", "ZC4", "ZC14", "None"),
        ("rr6", "ZC3", "ZC6", "ZC36", "None"),
        ("rr7", "ZC5", "ZC8", "ZC58", "None"),
    ],
    ("seed-61", "random-polymer"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "ZD6"),
        ("rr1", "ZD2", "ZD3", "ZD23", "ZD8"),
        ("rr2", "ZD4", "ZD5", "ZD45", "ZD0"),
        ("rr3", "ZD6", "ZD7", "ZD67", "ZD2"),
        ("rr4", "ZD8", "ZD9", "ZD89", "ZD4"),
        ("rr5", "ZD1", "ZD4", "ZD14", "ZD7"),
        ("rr6", "ZD3", "ZD6", "ZD36", "ZD9"),
        ("rr7", "ZD5", "ZD8", "ZD58", "ZD1"),
    ],
    ("seed-61", "shuffled-catalysts"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "ZD7"),
        ("rr1", "ZD2", "ZD3", "ZD23", "ZD9"),
        ("rr2", "ZD4", "ZD5", "ZD45", "ZD1"),
        ("rr3", "ZD6", "ZD7", "ZD67", "ZD3"),
        ("rr4", "ZD8", "ZD9", "ZD89", "ZD5"),
        ("rr5", "ZD1", "ZD4", "ZD14", "ZD8"),
        ("rr6", "ZD3", "ZD6", "ZD36", "ZD0"),
        ("rr7", "ZD5", "ZD8", "ZD58", "ZD2"),
    ],
    ("seed-61", "no-catalysis"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "None"),
        ("rr1", "ZD2", "ZD3", "ZD23", "None"),
        ("rr2", "ZD4", "ZD5", "ZD45", "None"),
        ("rr3", "ZD6", "ZD7", "ZD67", "None"),
        ("rr4", "ZD8", "ZD9", "ZD89", "None"),
        ("rr5", "ZD1", "ZD4", "ZD14", "None"),
        ("rr6", "ZD3", "ZD6", "ZD36", "None"),
        ("rr7", "ZD5", "ZD8", "ZD58", "None"),
    ],
    ("seed-67", "random-polymer"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "ZE6"),
        ("rr1", "ZE2", "ZE3", "ZE23", "ZE8"),
        ("rr2", "ZE4", "ZE5", "ZE45", "ZE0"),
        ("rr3", "ZE6", "ZE7", "ZE67", "ZE2"),
        ("rr4", "ZE8", "ZE9", "ZE89", "ZE4"),
        ("rr5", "ZE1", "ZE4", "ZE14", "ZE7"),
        ("rr6", "ZE3", "ZE6", "ZE36", "ZE9"),
        ("rr7", "ZE5", "ZE8", "ZE58", "ZE1"),
    ],
    ("seed-67", "shuffled-catalysts"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "ZE7"),
        ("rr1", "ZE2", "ZE3", "ZE23", "ZE9"),
        ("rr2", "ZE4", "ZE5", "ZE45", "ZE1"),
        ("rr3", "ZE6", "ZE7", "ZE67", "ZE3"),
        ("rr4", "ZE8", "ZE9", "ZE89", "ZE5"),
        ("rr5", "ZE1", "ZE4", "ZE14", "ZE8"),
        ("rr6", "ZE3", "ZE6", "ZE36", "ZE0"),
        ("rr7", "ZE5", "ZE8", "ZE58", "ZE2"),
    ],
    ("seed-67", "no-catalysis"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "None"),
        ("rr1", "ZE2", "ZE3", "ZE23", "None"),
        ("rr2", "ZE4", "ZE5", "ZE45", "None"),
        ("rr3", "ZE6", "ZE7", "ZE67", "None"),
        ("rr4", "ZE8", "ZE9", "ZE89", "None"),
        ("rr5", "ZE1", "ZE4", "ZE14", "None"),
        ("rr6", "ZE3", "ZE6", "ZE36", "None"),
        ("rr7", "ZE5", "ZE8", "ZE58", "None"),
    ],

    ("seed-71", "random-polymer"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "ZF6"),
        ("rr1", "ZF2", "ZF3", "ZF23", "ZF8"),
        ("rr2", "ZF4", "ZF5", "ZF45", "ZF0"),
        ("rr3", "ZF6", "ZF7", "ZF67", "ZF2"),
        ("rr4", "ZF8", "ZF9", "ZF89", "ZF4"),
        ("rr5", "ZF1", "ZF4", "ZF14", "ZF7"),
        ("rr6", "ZF3", "ZF6", "ZF36", "ZF9"),
        ("rr7", "ZF5", "ZF8", "ZF58", "ZF1"),
    ],
    ("seed-71", "shuffled-catalysts"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "ZF7"),
        ("rr1", "ZF2", "ZF3", "ZF23", "ZF9"),
        ("rr2", "ZF4", "ZF5", "ZF45", "ZF1"),
        ("rr3", "ZF6", "ZF7", "ZF67", "ZF3"),
        ("rr4", "ZF8", "ZF9", "ZF89", "ZF5"),
        ("rr5", "ZF1", "ZF4", "ZF14", "ZF8"),
        ("rr6", "ZF3", "ZF6", "ZF36", "ZF0"),
        ("rr7", "ZF5", "ZF8", "ZF58", "ZF2"),
    ],
    ("seed-71", "no-catalysis"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "None"),
        ("rr1", "ZF2", "ZF3", "ZF23", "None"),
        ("rr2", "ZF4", "ZF5", "ZF45", "None"),
        ("rr3", "ZF6", "ZF7", "ZF67", "None"),
        ("rr4", "ZF8", "ZF9", "ZF89", "None"),
        ("rr5", "ZF1", "ZF4", "ZF14", "None"),
        ("rr6", "ZF3", "ZF6", "ZF36", "None"),
        ("rr7", "ZF5", "ZF8", "ZF58", "None"),
    ],

    ("seed-73", "random-polymer"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "ZG6"),
        ("rr1", "ZG2", "ZG3", "ZG23", "ZG8"),
        ("rr2", "ZG4", "ZG5", "ZG45", "ZG0"),
        ("rr3", "ZG6", "ZG7", "ZG67", "ZG2"),
        ("rr4", "ZG8", "ZG9", "ZG89", "ZG4"),
        ("rr5", "ZG1", "ZG4", "ZG14", "ZG7"),
        ("rr6", "ZG3", "ZG6", "ZG36", "ZG9"),
        ("rr7", "ZG5", "ZG8", "ZG58", "ZG1"),
    ],
    ("seed-73", "shuffled-catalysts"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "ZG7"),
        ("rr1", "ZG2", "ZG3", "ZG23", "ZG9"),
        ("rr2", "ZG4", "ZG5", "ZG45", "ZG1"),
        ("rr3", "ZG6", "ZG7", "ZG67", "ZG3"),
        ("rr4", "ZG8", "ZG9", "ZG89", "ZG5"),
        ("rr5", "ZG1", "ZG4", "ZG14", "ZG8"),
        ("rr6", "ZG3", "ZG6", "ZG36", "ZG0"),
        ("rr7", "ZG5", "ZG8", "ZG58", "ZG2"),
    ],
    ("seed-73", "no-catalysis"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "None"),
        ("rr1", "ZG2", "ZG3", "ZG23", "None"),
        ("rr2", "ZG4", "ZG5", "ZG45", "None"),
        ("rr3", "ZG6", "ZG7", "ZG67", "None"),
        ("rr4", "ZG8", "ZG9", "ZG89", "None"),
        ("rr5", "ZG1", "ZG4", "ZG14", "None"),
        ("rr6", "ZG3", "ZG6", "ZG36", "None"),
        ("rr7", "ZG5", "ZG8", "ZG58", "None"),
    ],
    ("seed-79", "random-polymer"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "ZH6"),
        ("rr1", "ZH2", "ZH3", "ZH23", "ZH8"),
        ("rr2", "ZH4", "ZH5", "ZH45", "ZH0"),
        ("rr3", "ZH6", "ZH7", "ZH67", "ZH2"),
        ("rr4", "ZH8", "ZH9", "ZH89", "ZH4"),
        ("rr5", "ZH1", "ZH4", "ZH14", "ZH7"),
        ("rr6", "ZH3", "ZH6", "ZH36", "ZH9"),
        ("rr7", "ZH5", "ZH8", "ZH58", "ZH1"),
    ],
    ("seed-79", "shuffled-catalysts"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "ZH7"),
        ("rr1", "ZH2", "ZH3", "ZH23", "ZH9"),
        ("rr2", "ZH4", "ZH5", "ZH45", "ZH1"),
        ("rr3", "ZH6", "ZH7", "ZH67", "ZH3"),
        ("rr4", "ZH8", "ZH9", "ZH89", "ZH5"),
        ("rr5", "ZH1", "ZH4", "ZH14", "ZH8"),
        ("rr6", "ZH3", "ZH6", "ZH36", "ZH0"),
        ("rr7", "ZH5", "ZH8", "ZH58", "ZH2"),
    ],
    ("seed-79", "no-catalysis"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "None"),
        ("rr1", "ZH2", "ZH3", "ZH23", "None"),
        ("rr2", "ZH4", "ZH5", "ZH45", "None"),
        ("rr3", "ZH6", "ZH7", "ZH67", "None"),
        ("rr4", "ZH8", "ZH9", "ZH89", "None"),
        ("rr5", "ZH1", "ZH4", "ZH14", "None"),
        ("rr6", "ZH3", "ZH6", "ZH36", "None"),
        ("rr7", "ZH5", "ZH8", "ZH58", "None"),
    ],

}

ACTIVE_PAIRS = {
    ("seed-7", "random-polymer"): {(0, 1)},
    ("seed-11", "random-polymer"): {(0, 1), (2, 3)},
    ("seed-13", "random-polymer"): {(0, 1), (2, 3)},
    ("seed-17", "random-polymer"): {(0, 1), (2, 3)},
}

EVENTS = {
    ("seed-7", "random-polymer"): "(event 0 rr0 P0 P1 P01 P10)\n(event 1 rr1 P2 P3 P10 P01)\n",
}

@dataclass(frozen=True)
class RunSpec:
    key: str
    seed: str
    rule_count: int
    family: str
    run_id: str
    summary: str


def control_suffix(family: str) -> str:
    return {"random-polymer": "random", "shuffled-catalysts": "shuffled", "no-catalysis": "no-catalysis"}[family]


def count_word(count: int) -> str:
    return {1: "one", 2: "two"}.get(count, str(count))


def build_specs() -> list[RunSpec]:
    specs: list[RunSpec] = []
    for seed, count in [("seed-7", 4), ("seed-11", 6), ("seed-13", 8), ("seed-17", 8), ("seed-19", 8), ("seed-23", 8), ("seed-29", 8), ("seed-31", 8), ("seed-37", 8), ("seed-41", 8), ("seed-43", 8), ("seed-47", 8), ("seed-53", 8), ("seed-59", 8), ("seed-61", 8), ("seed-67", 8), ("seed-71", 8), ("seed-73", 8), ("seed-79", 8)]:
        for family in ["random-polymer", "shuffled-catalysts", "no-catalysis"]:
            suffix = control_suffix(family)
            if seed == "seed-7":
                run_id = f"exp02-small-{suffix}"
            else:
                run_id = f"exp02-{seed}-rules-{count}-{suffix}"
            active = len(ACTIVE_PAIRS.get((seed, family), set()))
            if family == "random-polymer":
                summary = f"{seed}-rules-{count}-random-has-{count_word(active)}-active-pairs"
            else:
                summary = f"{seed}-rules-{count}-{suffix}-control-has-zero-active-pairs"
            if seed == "seed-7" and family == "random-polymer":
                summary = "seed-7-random-has-one-active-pair"
            elif seed == "seed-7" and family == "shuffled-catalysts":
                summary = "shuffled-control-has-zero-active-pairs"
            elif seed == "seed-7" and family == "no-catalysis":
                summary = "no-catalysis-control-has-zero-active-pairs"
            specs.append(RunSpec(f"{seed}-{suffix}", seed, count, family, run_id, summary))
    return specs


def rule_atom(rule: tuple[str, str, str, str, str]) -> str:
    rid, a, b, product, catalyst = rule
    return f"(rule {rid} {a} {b} {product} {catalyst})"


def acs_atoms(seed: str, family: str) -> str:
    rules = RULES[(seed, family)]
    active_pairs = ACTIVE_PAIRS.get((seed, family), set())
    lines = []
    for i in range(len(rules)):
        for j in range(i + 1, len(rules)):
            status = "active" if (i, j) in active_pairs else "rejected"
            products = f"({rules[i][3]} {rules[j][3]})"
            catalysts = f"({rules[i][4]} {rules[j][4]})"
            lines.append(
                f"(acs-candidate pair-{i}-{j} ({rule_atom(rules[i])} {rule_atom(rules[j])}) {products} {catalysts} {status})"
            )
    return "\n".join(lines) + "\n"


def metric_atoms(spec: RunSpec) -> str:
    active = len(ACTIVE_PAIRS.get((spec.seed, spec.family), set()))
    body = (
        f"(metric active-acs-count {spec.run_id} {active})\n"
        f"(metric control-family {spec.run_id} {spec.family})\n"
        f"(metric rule-count {spec.run_id} {spec.rule_count})\n"
    )
    if spec.seed == "seed-17":
        body += f"(metric generation-seam {spec.run_id} seed-to-components)\n"
    if spec.seed in {"seed-19", "seed-23"}:
        body += f"(metric generation-seam {spec.run_id} seed-to-components)\n"
        body += f"(metric sweep-kind {spec.run_id} generated-unplanted-control)\n"
    if spec.seed in {"seed-29", "seed-31", "seed-37", "seed-41", "seed-43", "seed-47", "seed-53", "seed-59", "seed-61", "seed-67", "seed-71", "seed-73", "seed-79"}:
        body += f"(metric generation-seam {spec.run_id} factored-seed-template)\n"
        body += f"(metric sweep-kind {spec.run_id} generated-unplanted-control)\n"
    return body


def write_file(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(FILE_HEADER + (body if body else EMPTY), encoding="utf-8")


def write_run(output_root: Path, spec: RunSpec) -> None:
    run_dir = output_root / spec.run_id
    write_file(run_dir / "CONFIG.metta", f"(run-config {spec.run_id} exp02 ({spec.seed}) 1 (candidate-cap {spec.rule_count} 1) {spec.family})\n")
    write_file(run_dir / "MANIFEST.metta", f"(run-manifest {spec.run_id} config-hash-{spec.run_id} petta-local swi-9-3-36 scripts-run-exp02-sh 0)\n")
    write_file(run_dir / "EVENTS.metta", EVENTS.get((spec.seed, spec.family), ""))
    write_file(run_dir / "ABUNDANCES.metta", ABUNDANCES_BY_SEED[spec.seed])
    write_file(run_dir / "METRICS.metta", metric_atoms(spec))
    write_file(run_dir / "ACS.metta", acs_atoms(spec.seed, spec.family))
    write_file(run_dir / "ABLATIONS.metta", "")
    write_file(run_dir / "SUMMARY.metta", f"(run-summary {spec.run_id} passed {spec.summary} True)\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    args = parser.parse_args()

    specs = build_specs()
    for spec in specs:
        write_run(args.output_root, spec)

    print(f"wrote {len(specs)} exp02 run-contract directories under {args.output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
