#!/usr/bin/env python3
"""Write exp02 PeTTa run-contract atoms to per-run files.

This is intentionally a thin host harness: chemistry, ACS scanning, metrics, and
run-record shapes are defined and tested in PeTTa.  The harness serializes the
PeTTa-tested sweep points into the v0.1 per-run file convention; the active-pair
labels below mirror exp02 smoke-test expectations rather than driving chemistry.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "experiments" / "exp02_small_sweep_20260630" / "runs"

FILE_HEADER = "; Generated by scripts/write_exp02_contract_files.py from PeTTa-tested exp02 run-contract atoms.\n"
EMPTY = "; Intentionally empty for this run.\n"

ABUNDANCES_BY_SEED = {
    "seed-7": "(abundance-snapshot 0 ((mol P0 2) (mol P1 1) (mol P2 1) (mol P3 1) (mol P01 0) (mol P10 1)))\n",
    "seed-11": "(abundance-snapshot 0 ((mol Q0 2) (mol Q1 1) (mol Q2 1) (mol Q3 1) (mol Q01 0) (mol Q10 1)))\n",
    "seed-13": "(abundance-snapshot 0 ((mol R0 2) (mol R1 1) (mol R2 1) (mol R3 1) (mol R01 0) (mol R10 1)))\n",
    "seed-17": "(abundance-snapshot 0 ((mol S0 2) (mol S1 1) (mol S2 1) (mol S3 1) (mol S01 0) (mol S10 1)))\n",
    "seed-19": "(abundance-snapshot 0 ((mol T0 2) (mol T1 1) (mol T2 1) (mol T3 1) (mol T01 0) (mol T23 0)))\n",
    "seed-23": "(abundance-snapshot 0 ((mol U0 2) (mol U1 1) (mol U2 1) (mol U3 1) (mol U01 0) (mol U23 0)))\n",
    "seed-29": "(abundance-snapshot 0 ((mol V0 2) (mol V1 1) (mol V2 1) (mol V3 1) (mol V01 0) (mol V23 0)))\n",
    "seed-31": "(abundance-snapshot 0 ((mol W0 2) (mol W1 1) (mol W2 1) (mol W3 1) (mol W01 0) (mol W23 0)))\n",
    "seed-37": "(abundance-snapshot 0 ((mol X0 2) (mol X1 1) (mol X2 1) (mol X3 1) (mol X01 0) (mol X23 0)))\n",
    "seed-41": "(abundance-snapshot 0 ((mol Y0 2) (mol Y1 1) (mol Y2 1) (mol Y3 1) (mol Y01 0) (mol Y23 0)))\n",
    "seed-43": "(abundance-snapshot 0 ((mol Z0 2) (mol Z1 1) (mol Z2 1) (mol Z3 1) (mol Z01 0) (mol Z23 0)))\n",
    "seed-47": "(abundance-snapshot 0 ((mol ZA0 2) (mol ZA1 1) (mol ZA2 1) (mol ZA3 1) (mol ZA01 0) (mol ZA23 0)))\n",
    "seed-53": "(abundance-snapshot 0 ((mol ZB0 2) (mol ZB1 1) (mol ZB2 1) (mol ZB3 1) (mol ZB01 0) (mol ZB23 0)))\n",
    "seed-59": "(abundance-snapshot 0 ((mol ZC0 2) (mol ZC1 1) (mol ZC2 1) (mol ZC3 1) (mol ZC01 0) (mol ZC23 0)))\n",
    "seed-61": "(abundance-snapshot 0 ((mol ZD0 2) (mol ZD1 1) (mol ZD2 1) (mol ZD3 1) (mol ZD01 0) (mol ZD23 0)))\n",
    "seed-67": "(abundance-snapshot 0 ((mol ZE0 2) (mol ZE1 1) (mol ZE2 1) (mol ZE3 1) (mol ZE01 0) (mol ZE23 0)))\n",
    "seed-71": "(abundance-snapshot 0 ((mol ZF0 2) (mol ZF1 1) (mol ZF2 1) (mol ZF3 1) (mol ZF01 0) (mol ZF23 0)))\n",
    "seed-73": "(abundance-snapshot 0 ((mol ZG0 2) (mol ZG1 1) (mol ZG2 1) (mol ZG3 1) (mol ZG01 0) (mol ZG23 0)))\n",
    "seed-79": "(abundance-snapshot 0 ((mol ZH0 2) (mol ZH1 1) (mol ZH2 1) (mol ZH3 1) (mol ZH01 0) (mol ZH23 0)))\n",
    "seed-83": "(abundance-snapshot 0 ((mol ZI0 2) (mol ZI1 1) (mol ZI2 1) (mol ZI3 1) (mol ZI01 0) (mol ZI23 0)))\n",
    "seed-89": "(abundance-snapshot 0 ((mol ZJ0 2) (mol ZJ1 1) (mol ZJ2 1) (mol ZJ3 1) (mol ZJ01 0) (mol ZJ23 0)))\n",
    "seed-97": "(abundance-snapshot 0 ((mol ZK0 2) (mol ZK1 1) (mol ZK2 1) (mol ZK3 1) (mol ZK01 0) (mol ZK23 0)))\n",
    "seed-101": "(abundance-snapshot 0 ((mol ZL0 2) (mol ZL1 1) (mol ZL2 1) (mol ZL3 1) (mol ZL01 0) (mol ZL23 0)))\n",
    "seed-103": "(abundance-snapshot 0 ((mol ZM0 2) (mol ZM1 1) (mol ZM2 1) (mol ZM3 1) (mol ZM01 0) (mol ZM23 0)))\n",
    "seed-107": "(abundance-snapshot 0 ((mol ZN0 2) (mol ZN1 1) (mol ZN2 1) (mol ZN3 1) (mol ZN01 0) (mol ZN23 0)))\n",
    "seed-109": "(abundance-snapshot 0 ((mol ZO0 2) (mol ZO1 1) (mol ZO2 1) (mol ZO3 1) (mol ZO01 0) (mol ZO23 0)))\n",
    "seed-113": "(abundance-snapshot 0 ((mol ZP0 2) (mol ZP1 1) (mol ZP2 1) (mol ZP3 1) (mol ZP01 0) (mol ZP23 0)))\n",
    "seed-127": "(abundance-snapshot 0 ((mol ZQ0 2) (mol ZQ1 1) (mol ZQ2 1) (mol ZQ3 1) (mol ZQ01 0) (mol ZQ23 0)))\n",
    "seed-131": "(abundance-snapshot 0 ((mol ZR0 2) (mol ZR1 1) (mol ZR2 1) (mol ZR3 1) (mol ZR01 0) (mol ZR23 0)))\n",
    "seed-137": "(abundance-snapshot 0 ((mol ZS0 2) (mol ZS1 1) (mol ZS2 1) (mol ZS3 1) (mol ZS01 0) (mol ZS23 0)))\n",
    "seed-139": "(abundance-snapshot 0 ((mol ZT0 2) (mol ZT1 1) (mol ZT2 1) (mol ZT3 1) (mol ZT01 0) (mol ZT23 0)))\n",
    "seed-149": "(abundance-snapshot 0 ((mol ZU0 2) (mol ZU1 1) (mol ZU2 1) (mol ZU3 1) (mol ZU01 0) (mol ZU23 0)))\n",
    "seed-151": "(abundance-snapshot 0 ((mol ZV0 2) (mol ZV1 1) (mol ZV2 1) (mol ZV3 1) (mol ZV01 0) (mol ZV23 0)))\n",
    "seed-157": "(abundance-snapshot 0 ((mol ZW0 2) (mol ZW1 1) (mol ZW2 1) (mol ZW3 1) (mol ZW01 0) (mol ZW23 0)))\n",
    "seed-163": "(abundance-snapshot 0 ((mol ZX0 2) (mol ZX1 1) (mol ZX2 1) (mol ZX3 1) (mol ZX01 0) (mol ZX23 0)))\n",
}

RULES = {
    ("seed-7", "random-polymer"): [
        ("rr0", "P0", "P1", "P01", "P10"),
        ("rr1", "P2", "P3", "P10", "P01"),
        ("rr2", "P0", "P3", "P03", "P2"),
        ("rr3", "P1", "P2", "P12", "P0"),
    ],
    ("seed-7", "shuffled-catalysts"): [
        ("sr0", "P0", "P1", "P01", "P2"),
        ("sr1", "P2", "P3", "P10", "P0"),
        ("sr2", "P0", "P3", "P03", "P10"),
        ("sr3", "P1", "P2", "P12", "P3"),
    ],
    ("seed-7", "no-catalysis"): [
        ("nr0", "P0", "P1", "P01", "None"),
        ("nr1", "P2", "P3", "P10", "None"),
        ("nr2", "P0", "P3", "P03", "None"),
        ("nr3", "P1", "P2", "P12", "None"),
    ],
    ("seed-11", "random-polymer"): [
        ("rr0", "Q0", "Q1", "Q01", "Q10"),
        ("rr1", "Q2", "Q3", "Q10", "Q01"),
        ("rr2", "Q4", "Q5", "Q45", "Q54"),
        ("rr3", "Q6", "Q7", "Q54", "Q45"),
        ("rr4", "Q0", "Q5", "Q05", "Q2"),
        ("rr5", "Q1", "Q6", "Q16", "Q3"),
    ],
    ("seed-11", "shuffled-catalysts"): [
        ("sr0", "Q0", "Q1", "Q01", "Q2"),
        ("sr1", "Q2", "Q3", "Q10", "Q4"),
        ("sr2", "Q4", "Q5", "Q45", "Q6"),
        ("sr3", "Q6", "Q7", "Q54", "Q0"),
        ("sr4", "Q0", "Q5", "Q05", "Q10"),
        ("sr5", "Q1", "Q6", "Q16", "Q54"),
    ],
    ("seed-11", "no-catalysis"): [
        ("nr0", "Q0", "Q1", "Q01", "None"),
        ("nr1", "Q2", "Q3", "Q10", "None"),
        ("nr2", "Q4", "Q5", "Q45", "None"),
        ("nr3", "Q6", "Q7", "Q54", "None"),
        ("nr4", "Q0", "Q5", "Q05", "None"),
        ("nr5", "Q1", "Q6", "Q16", "None"),
    ],
    ("seed-13", "random-polymer"): [
        ("rr0", "R0", "R1", "R01", "R10"),
        ("rr1", "R2", "R3", "R10", "R01"),
        ("rr2", "R4", "R5", "R45", "R54"),
        ("rr3", "R6", "R7", "R54", "R45"),
        ("rr4", "R8", "R9", "R89", "R2"),
        ("rr5", "R0", "R5", "R05", "R3"),
        ("rr6", "R1", "R6", "R16", "R5"),
        ("rr7", "R2", "R7", "R27", "R9"),
    ],
    ("seed-13", "shuffled-catalysts"): [
        ("rr0", "R0", "R1", "R01", "R2"),
        ("rr1", "R2", "R3", "R10", "R4"),
        ("rr2", "R4", "R5", "R45", "R6"),
        ("rr3", "R6", "R7", "R54", "R8"),
        ("rr4", "R8", "R9", "R89", "R10"),
        ("rr5", "R0", "R5", "R05", "R01"),
        ("rr6", "R1", "R6", "R16", "R45"),
        ("rr7", "R2", "R7", "R27", "R54"),
    ],
    ("seed-13", "no-catalysis"): [
        ("rr0", "R0", "R1", "R01", "None"),
        ("rr1", "R2", "R3", "R10", "None"),
        ("rr2", "R4", "R5", "R45", "None"),
        ("rr3", "R6", "R7", "R54", "None"),
        ("rr4", "R8", "R9", "R89", "None"),
        ("rr5", "R0", "R5", "R05", "None"),
        ("rr6", "R1", "R6", "R16", "None"),
        ("rr7", "R2", "R7", "R27", "None"),
    ],
    ("seed-17", "random-polymer"): [
        ("rr0", "S0", "S1", "S01", "S10"),
        ("rr1", "S2", "S3", "S10", "S01"),
        ("rr2", "S4", "S5", "S45", "S54"),
        ("rr3", "S6", "S7", "S54", "S45"),
        ("rr4", "S8", "S9", "S89", "S2"),
        ("rr5", "S0", "S5", "S05", "S3"),
        ("rr6", "S1", "S6", "S16", "S5"),
        ("rr7", "S2", "S7", "S27", "S9"),
    ],
    ("seed-17", "shuffled-catalysts"): [
        ("rr0", "S0", "S1", "S01", "S2"),
        ("rr1", "S2", "S3", "S10", "S4"),
        ("rr2", "S4", "S5", "S45", "S6"),
        ("rr3", "S6", "S7", "S54", "S8"),
        ("rr4", "S8", "S9", "S89", "S10"),
        ("rr5", "S0", "S5", "S05", "S01"),
        ("rr6", "S1", "S6", "S16", "S45"),
        ("rr7", "S2", "S7", "S27", "S54"),
    ],
    ("seed-17", "no-catalysis"): [
        ("rr0", "S0", "S1", "S01", "None"),
        ("rr1", "S2", "S3", "S10", "None"),
        ("rr2", "S4", "S5", "S45", "None"),
        ("rr3", "S6", "S7", "S54", "None"),
        ("rr4", "S8", "S9", "S89", "None"),
        ("rr5", "S0", "S5", "S05", "None"),
        ("rr6", "S1", "S6", "S16", "None"),
        ("rr7", "S2", "S7", "S27", "None"),
    ],
    ("seed-19", "random-polymer"): [
        ("rr0", "T0", "T1", "T01", "T2"),
        ("rr1", "T2", "T3", "T23", "T4"),
        ("rr2", "T4", "T5", "T45", "T6"),
        ("rr3", "T6", "T7", "T67", "T8"),
        ("rr4", "T8", "T9", "T89", "T0"),
        ("rr5", "T1", "T4", "T14", "T3"),
        ("rr6", "T3", "T6", "T36", "T5"),
        ("rr7", "T5", "T8", "T58", "T7"),
    ],
    ("seed-19", "shuffled-catalysts"): [
        ("rr0", "T0", "T1", "T01", "T3"),
        ("rr1", "T2", "T3", "T23", "T5"),
        ("rr2", "T4", "T5", "T45", "T7"),
        ("rr3", "T6", "T7", "T67", "T9"),
        ("rr4", "T8", "T9", "T89", "T1"),
        ("rr5", "T1", "T4", "T14", "T6"),
        ("rr6", "T3", "T6", "T36", "T8"),
        ("rr7", "T5", "T8", "T58", "T0"),
    ],
    ("seed-19", "no-catalysis"): [
        ("rr0", "T0", "T1", "T01", "None"),
        ("rr1", "T2", "T3", "T23", "None"),
        ("rr2", "T4", "T5", "T45", "None"),
        ("rr3", "T6", "T7", "T67", "None"),
        ("rr4", "T8", "T9", "T89", "None"),
        ("rr5", "T1", "T4", "T14", "None"),
        ("rr6", "T3", "T6", "T36", "None"),
        ("rr7", "T5", "T8", "T58", "None"),
    ],
    ("seed-23", "random-polymer"): [
        ("rr0", "U0", "U1", "U01", "U4"),
        ("rr1", "U2", "U3", "U23", "U6"),
        ("rr2", "U4", "U5", "U45", "U8"),
        ("rr3", "U6", "U7", "U67", "U0"),
        ("rr4", "U8", "U9", "U89", "U2"),
        ("rr5", "U1", "U4", "U14", "U5"),
        ("rr6", "U3", "U6", "U36", "U7"),
        ("rr7", "U5", "U8", "U58", "U9"),
    ],
    ("seed-23", "shuffled-catalysts"): [
        ("rr0", "U0", "U1", "U01", "U5"),
        ("rr1", "U2", "U3", "U23", "U7"),
        ("rr2", "U4", "U5", "U45", "U9"),
        ("rr3", "U6", "U7", "U67", "U1"),
        ("rr4", "U8", "U9", "U89", "U3"),
        ("rr5", "U1", "U4", "U14", "U6"),
        ("rr6", "U3", "U6", "U36", "U8"),
        ("rr7", "U5", "U8", "U58", "U0"),
    ],
    ("seed-23", "no-catalysis"): [
        ("rr0", "U0", "U1", "U01", "None"),
        ("rr1", "U2", "U3", "U23", "None"),
        ("rr2", "U4", "U5", "U45", "None"),
        ("rr3", "U6", "U7", "U67", "None"),
        ("rr4", "U8", "U9", "U89", "None"),
        ("rr5", "U1", "U4", "U14", "None"),
        ("rr6", "U3", "U6", "U36", "None"),
        ("rr7", "U5", "U8", "U58", "None"),
    ],

    ("seed-29", "random-polymer"): [
        ("rr0", "V0", "V1", "V01", "V6"),
        ("rr1", "V2", "V3", "V23", "V8"),
        ("rr2", "V4", "V5", "V45", "V0"),
        ("rr3", "V6", "V7", "V67", "V2"),
        ("rr4", "V8", "V9", "V89", "V4"),
        ("rr5", "V1", "V4", "V14", "V7"),
        ("rr6", "V3", "V6", "V36", "V9"),
        ("rr7", "V5", "V8", "V58", "V1"),
    ],
    ("seed-29", "shuffled-catalysts"): [
        ("rr0", "V0", "V1", "V01", "V7"),
        ("rr1", "V2", "V3", "V23", "V9"),
        ("rr2", "V4", "V5", "V45", "V1"),
        ("rr3", "V6", "V7", "V67", "V3"),
        ("rr4", "V8", "V9", "V89", "V5"),
        ("rr5", "V1", "V4", "V14", "V8"),
        ("rr6", "V3", "V6", "V36", "V0"),
        ("rr7", "V5", "V8", "V58", "V2"),
    ],
    ("seed-29", "no-catalysis"): [
        ("rr0", "V0", "V1", "V01", "None"),
        ("rr1", "V2", "V3", "V23", "None"),
        ("rr2", "V4", "V5", "V45", "None"),
        ("rr3", "V6", "V7", "V67", "None"),
        ("rr4", "V8", "V9", "V89", "None"),
        ("rr5", "V1", "V4", "V14", "None"),
        ("rr6", "V3", "V6", "V36", "None"),
        ("rr7", "V5", "V8", "V58", "None"),
    ],


    ("seed-31", "random-polymer"): [
        ("rr0", "W0", "W1", "W01", "W6"),
        ("rr1", "W2", "W3", "W23", "W8"),
        ("rr2", "W4", "W5", "W45", "W0"),
        ("rr3", "W6", "W7", "W67", "W2"),
        ("rr4", "W8", "W9", "W89", "W4"),
        ("rr5", "W1", "W4", "W14", "W7"),
        ("rr6", "W3", "W6", "W36", "W9"),
        ("rr7", "W5", "W8", "W58", "W1"),
    ],
    ("seed-31", "shuffled-catalysts"): [
        ("rr0", "W0", "W1", "W01", "W7"),
        ("rr1", "W2", "W3", "W23", "W9"),
        ("rr2", "W4", "W5", "W45", "W1"),
        ("rr3", "W6", "W7", "W67", "W3"),
        ("rr4", "W8", "W9", "W89", "W5"),
        ("rr5", "W1", "W4", "W14", "W8"),
        ("rr6", "W3", "W6", "W36", "W0"),
        ("rr7", "W5", "W8", "W58", "W2"),
    ],
    ("seed-31", "no-catalysis"): [
        ("rr0", "W0", "W1", "W01", "None"),
        ("rr1", "W2", "W3", "W23", "None"),
        ("rr2", "W4", "W5", "W45", "None"),
        ("rr3", "W6", "W7", "W67", "None"),
        ("rr4", "W8", "W9", "W89", "None"),
        ("rr5", "W1", "W4", "W14", "None"),
        ("rr6", "W3", "W6", "W36", "None"),
        ("rr7", "W5", "W8", "W58", "None"),
    ],

    ("seed-37", "random-polymer"): [
        ("rr0", "X0", "X1", "X01", "X6"),
        ("rr1", "X2", "X3", "X23", "X8"),
        ("rr2", "X4", "X5", "X45", "X0"),
        ("rr3", "X6", "X7", "X67", "X2"),
        ("rr4", "X8", "X9", "X89", "X4"),
        ("rr5", "X1", "X4", "X14", "X7"),
        ("rr6", "X3", "X6", "X36", "X9"),
        ("rr7", "X5", "X8", "X58", "X1"),
    ],
    ("seed-37", "shuffled-catalysts"): [
        ("rr0", "X0", "X1", "X01", "X7"),
        ("rr1", "X2", "X3", "X23", "X9"),
        ("rr2", "X4", "X5", "X45", "X1"),
        ("rr3", "X6", "X7", "X67", "X3"),
        ("rr4", "X8", "X9", "X89", "X5"),
        ("rr5", "X1", "X4", "X14", "X8"),
        ("rr6", "X3", "X6", "X36", "X0"),
        ("rr7", "X5", "X8", "X58", "X2"),
    ],
    ("seed-37", "no-catalysis"): [
        ("rr0", "X0", "X1", "X01", "None"),
        ("rr1", "X2", "X3", "X23", "None"),
        ("rr2", "X4", "X5", "X45", "None"),
        ("rr3", "X6", "X7", "X67", "None"),
        ("rr4", "X8", "X9", "X89", "None"),
        ("rr5", "X1", "X4", "X14", "None"),
        ("rr6", "X3", "X6", "X36", "None"),
        ("rr7", "X5", "X8", "X58", "None"),
    ],

    ("seed-41", "random-polymer"): [
        ("rr0", "Y0", "Y1", "Y01", "Y6"),
        ("rr1", "Y2", "Y3", "Y23", "Y8"),
        ("rr2", "Y4", "Y5", "Y45", "Y0"),
        ("rr3", "Y6", "Y7", "Y67", "Y2"),
        ("rr4", "Y8", "Y9", "Y89", "Y4"),
        ("rr5", "Y1", "Y4", "Y14", "Y7"),
        ("rr6", "Y3", "Y6", "Y36", "Y9"),
        ("rr7", "Y5", "Y8", "Y58", "Y1"),
    ],
    ("seed-41", "shuffled-catalysts"): [
        ("rr0", "Y0", "Y1", "Y01", "Y7"),
        ("rr1", "Y2", "Y3", "Y23", "Y9"),
        ("rr2", "Y4", "Y5", "Y45", "Y1"),
        ("rr3", "Y6", "Y7", "Y67", "Y3"),
        ("rr4", "Y8", "Y9", "Y89", "Y5"),
        ("rr5", "Y1", "Y4", "Y14", "Y8"),
        ("rr6", "Y3", "Y6", "Y36", "Y0"),
        ("rr7", "Y5", "Y8", "Y58", "Y2"),
    ],
    ("seed-41", "no-catalysis"): [
        ("rr0", "Y0", "Y1", "Y01", "None"),
        ("rr1", "Y2", "Y3", "Y23", "None"),
        ("rr2", "Y4", "Y5", "Y45", "None"),
        ("rr3", "Y6", "Y7", "Y67", "None"),
        ("rr4", "Y8", "Y9", "Y89", "None"),
        ("rr5", "Y1", "Y4", "Y14", "None"),
        ("rr6", "Y3", "Y6", "Y36", "None"),
        ("rr7", "Y5", "Y8", "Y58", "None"),
    ],
    ("seed-43", "random-polymer"): [
        ("rr0", "Z0", "Z1", "Z01", "Z6"),
        ("rr1", "Z2", "Z3", "Z23", "Z8"),
        ("rr2", "Z4", "Z5", "Z45", "Z0"),
        ("rr3", "Z6", "Z7", "Z67", "Z2"),
        ("rr4", "Z8", "Z9", "Z89", "Z4"),
        ("rr5", "Z1", "Z4", "Z14", "Z7"),
        ("rr6", "Z3", "Z6", "Z36", "Z9"),
        ("rr7", "Z5", "Z8", "Z58", "Z1"),
    ],
    ("seed-43", "shuffled-catalysts"): [
        ("rr0", "Z0", "Z1", "Z01", "Z7"),
        ("rr1", "Z2", "Z3", "Z23", "Z9"),
        ("rr2", "Z4", "Z5", "Z45", "Z1"),
        ("rr3", "Z6", "Z7", "Z67", "Z3"),
        ("rr4", "Z8", "Z9", "Z89", "Z5"),
        ("rr5", "Z1", "Z4", "Z14", "Z8"),
        ("rr6", "Z3", "Z6", "Z36", "Z0"),
        ("rr7", "Z5", "Z8", "Z58", "Z2"),
    ],
    ("seed-43", "no-catalysis"): [
        ("rr0", "Z0", "Z1", "Z01", "None"),
        ("rr1", "Z2", "Z3", "Z23", "None"),
        ("rr2", "Z4", "Z5", "Z45", "None"),
        ("rr3", "Z6", "Z7", "Z67", "None"),
        ("rr4", "Z8", "Z9", "Z89", "None"),
        ("rr5", "Z1", "Z4", "Z14", "None"),
        ("rr6", "Z3", "Z6", "Z36", "None"),
        ("rr7", "Z5", "Z8", "Z58", "None"),
    ],    ("seed-47", "random-polymer"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "ZA6"),
        ("rr1", "ZA2", "ZA3", "ZA23", "ZA8"),
        ("rr2", "ZA4", "ZA5", "ZA45", "ZA0"),
        ("rr3", "ZA6", "ZA7", "ZA67", "ZA2"),
        ("rr4", "ZA8", "ZA9", "ZA89", "ZA4"),
        ("rr5", "ZA1", "ZA4", "ZA14", "ZA7"),
        ("rr6", "ZA3", "ZA6", "ZA36", "ZA9"),
        ("rr7", "ZA5", "ZA8", "ZA58", "ZA1"),
    ],
    ("seed-47", "shuffled-catalysts"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "ZA7"),
        ("rr1", "ZA2", "ZA3", "ZA23", "ZA9"),
        ("rr2", "ZA4", "ZA5", "ZA45", "ZA1"),
        ("rr3", "ZA6", "ZA7", "ZA67", "ZA3"),
        ("rr4", "ZA8", "ZA9", "ZA89", "ZA5"),
        ("rr5", "ZA1", "ZA4", "ZA14", "ZA8"),
        ("rr6", "ZA3", "ZA6", "ZA36", "ZA0"),
        ("rr7", "ZA5", "ZA8", "ZA58", "ZA2"),
    ],
    ("seed-47", "no-catalysis"): [
        ("rr0", "ZA0", "ZA1", "ZA01", "None"),
        ("rr1", "ZA2", "ZA3", "ZA23", "None"),
        ("rr2", "ZA4", "ZA5", "ZA45", "None"),
        ("rr3", "ZA6", "ZA7", "ZA67", "None"),
        ("rr4", "ZA8", "ZA9", "ZA89", "None"),
        ("rr5", "ZA1", "ZA4", "ZA14", "None"),
        ("rr6", "ZA3", "ZA6", "ZA36", "None"),
        ("rr7", "ZA5", "ZA8", "ZA58", "None"),
    ],


    ("seed-53", "random-polymer"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "ZB6"),
        ("rr1", "ZB2", "ZB3", "ZB23", "ZB8"),
        ("rr2", "ZB4", "ZB5", "ZB45", "ZB0"),
        ("rr3", "ZB6", "ZB7", "ZB67", "ZB2"),
        ("rr4", "ZB8", "ZB9", "ZB89", "ZB4"),
        ("rr5", "ZB1", "ZB4", "ZB14", "ZB7"),
        ("rr6", "ZB3", "ZB6", "ZB36", "ZB9"),
        ("rr7", "ZB5", "ZB8", "ZB58", "ZB1"),
    ],
    ("seed-53", "shuffled-catalysts"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "ZB7"),
        ("rr1", "ZB2", "ZB3", "ZB23", "ZB9"),
        ("rr2", "ZB4", "ZB5", "ZB45", "ZB1"),
        ("rr3", "ZB6", "ZB7", "ZB67", "ZB3"),
        ("rr4", "ZB8", "ZB9", "ZB89", "ZB5"),
        ("rr5", "ZB1", "ZB4", "ZB14", "ZB8"),
        ("rr6", "ZB3", "ZB6", "ZB36", "ZB0"),
        ("rr7", "ZB5", "ZB8", "ZB58", "ZB2"),
    ],
    ("seed-53", "no-catalysis"): [
        ("rr0", "ZB0", "ZB1", "ZB01", "None"),
        ("rr1", "ZB2", "ZB3", "ZB23", "None"),
        ("rr2", "ZB4", "ZB5", "ZB45", "None"),
        ("rr3", "ZB6", "ZB7", "ZB67", "None"),
        ("rr4", "ZB8", "ZB9", "ZB89", "None"),
        ("rr5", "ZB1", "ZB4", "ZB14", "None"),
        ("rr6", "ZB3", "ZB6", "ZB36", "None"),
        ("rr7", "ZB5", "ZB8", "ZB58", "None"),
    ],
    ("seed-59", "random-polymer"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "ZC6"),
        ("rr1", "ZC2", "ZC3", "ZC23", "ZC8"),
        ("rr2", "ZC4", "ZC5", "ZC45", "ZC0"),
        ("rr3", "ZC6", "ZC7", "ZC67", "ZC2"),
        ("rr4", "ZC8", "ZC9", "ZC89", "ZC4"),
        ("rr5", "ZC1", "ZC4", "ZC14", "ZC7"),
        ("rr6", "ZC3", "ZC6", "ZC36", "ZC9"),
        ("rr7", "ZC5", "ZC8", "ZC58", "ZC1"),
    ],
    ("seed-59", "shuffled-catalysts"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "ZC7"),
        ("rr1", "ZC2", "ZC3", "ZC23", "ZC9"),
        ("rr2", "ZC4", "ZC5", "ZC45", "ZC1"),
        ("rr3", "ZC6", "ZC7", "ZC67", "ZC3"),
        ("rr4", "ZC8", "ZC9", "ZC89", "ZC5"),
        ("rr5", "ZC1", "ZC4", "ZC14", "ZC8"),
        ("rr6", "ZC3", "ZC6", "ZC36", "ZC0"),
        ("rr7", "ZC5", "ZC8", "ZC58", "ZC2"),
    ],
    ("seed-59", "no-catalysis"): [
        ("rr0", "ZC0", "ZC1", "ZC01", "None"),
        ("rr1", "ZC2", "ZC3", "ZC23", "None"),
        ("rr2", "ZC4", "ZC5", "ZC45", "None"),
        ("rr3", "ZC6", "ZC7", "ZC67", "None"),
        ("rr4", "ZC8", "ZC9", "ZC89", "None"),
        ("rr5", "ZC1", "ZC4", "ZC14", "None"),
        ("rr6", "ZC3", "ZC6", "ZC36", "None"),
        ("rr7", "ZC5", "ZC8", "ZC58", "None"),
    ],
    ("seed-61", "random-polymer"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "ZD6"),
        ("rr1", "ZD2", "ZD3", "ZD23", "ZD8"),
        ("rr2", "ZD4", "ZD5", "ZD45", "ZD0"),
        ("rr3", "ZD6", "ZD7", "ZD67", "ZD2"),
        ("rr4", "ZD8", "ZD9", "ZD89", "ZD4"),
        ("rr5", "ZD1", "ZD4", "ZD14", "ZD7"),
        ("rr6", "ZD3", "ZD6", "ZD36", "ZD9"),
        ("rr7", "ZD5", "ZD8", "ZD58", "ZD1"),
    ],
    ("seed-61", "shuffled-catalysts"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "ZD7"),
        ("rr1", "ZD2", "ZD3", "ZD23", "ZD9"),
        ("rr2", "ZD4", "ZD5", "ZD45", "ZD1"),
        ("rr3", "ZD6", "ZD7", "ZD67", "ZD3"),
        ("rr4", "ZD8", "ZD9", "ZD89", "ZD5"),
        ("rr5", "ZD1", "ZD4", "ZD14", "ZD8"),
        ("rr6", "ZD3", "ZD6", "ZD36", "ZD0"),
        ("rr7", "ZD5", "ZD8", "ZD58", "ZD2"),
    ],
    ("seed-61", "no-catalysis"): [
        ("rr0", "ZD0", "ZD1", "ZD01", "None"),
        ("rr1", "ZD2", "ZD3", "ZD23", "None"),
        ("rr2", "ZD4", "ZD5", "ZD45", "None"),
        ("rr3", "ZD6", "ZD7", "ZD67", "None"),
        ("rr4", "ZD8", "ZD9", "ZD89", "None"),
        ("rr5", "ZD1", "ZD4", "ZD14", "None"),
        ("rr6", "ZD3", "ZD6", "ZD36", "None"),
        ("rr7", "ZD5", "ZD8", "ZD58", "None"),
    ],
    ("seed-67", "random-polymer"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "ZE6"),
        ("rr1", "ZE2", "ZE3", "ZE23", "ZE8"),
        ("rr2", "ZE4", "ZE5", "ZE45", "ZE0"),
        ("rr3", "ZE6", "ZE7", "ZE67", "ZE2"),
        ("rr4", "ZE8", "ZE9", "ZE89", "ZE4"),
        ("rr5", "ZE1", "ZE4", "ZE14", "ZE7"),
        ("rr6", "ZE3", "ZE6", "ZE36", "ZE9"),
        ("rr7", "ZE5", "ZE8", "ZE58", "ZE1"),
    ],
    ("seed-67", "shuffled-catalysts"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "ZE7"),
        ("rr1", "ZE2", "ZE3", "ZE23", "ZE9"),
        ("rr2", "ZE4", "ZE5", "ZE45", "ZE1"),
        ("rr3", "ZE6", "ZE7", "ZE67", "ZE3"),
        ("rr4", "ZE8", "ZE9", "ZE89", "ZE5"),
        ("rr5", "ZE1", "ZE4", "ZE14", "ZE8"),
        ("rr6", "ZE3", "ZE6", "ZE36", "ZE0"),
        ("rr7", "ZE5", "ZE8", "ZE58", "ZE2"),
    ],
    ("seed-67", "no-catalysis"): [
        ("rr0", "ZE0", "ZE1", "ZE01", "None"),
        ("rr1", "ZE2", "ZE3", "ZE23", "None"),
        ("rr2", "ZE4", "ZE5", "ZE45", "None"),
        ("rr3", "ZE6", "ZE7", "ZE67", "None"),
        ("rr4", "ZE8", "ZE9", "ZE89", "None"),
        ("rr5", "ZE1", "ZE4", "ZE14", "None"),
        ("rr6", "ZE3", "ZE6", "ZE36", "None"),
        ("rr7", "ZE5", "ZE8", "ZE58", "None"),
    ],

    ("seed-71", "random-polymer"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "ZF6"),
        ("rr1", "ZF2", "ZF3", "ZF23", "ZF8"),
        ("rr2", "ZF4", "ZF5", "ZF45", "ZF0"),
        ("rr3", "ZF6", "ZF7", "ZF67", "ZF2"),
        ("rr4", "ZF8", "ZF9", "ZF89", "ZF4"),
        ("rr5", "ZF1", "ZF4", "ZF14", "ZF7"),
        ("rr6", "ZF3", "ZF6", "ZF36", "ZF9"),
        ("rr7", "ZF5", "ZF8", "ZF58", "ZF1"),
    ],
    ("seed-71", "shuffled-catalysts"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "ZF7"),
        ("rr1", "ZF2", "ZF3", "ZF23", "ZF9"),
        ("rr2", "ZF4", "ZF5", "ZF45", "ZF1"),
        ("rr3", "ZF6", "ZF7", "ZF67", "ZF3"),
        ("rr4", "ZF8", "ZF9", "ZF89", "ZF5"),
        ("rr5", "ZF1", "ZF4", "ZF14", "ZF8"),
        ("rr6", "ZF3", "ZF6", "ZF36", "ZF0"),
        ("rr7", "ZF5", "ZF8", "ZF58", "ZF2"),
    ],
    ("seed-71", "no-catalysis"): [
        ("rr0", "ZF0", "ZF1", "ZF01", "None"),
        ("rr1", "ZF2", "ZF3", "ZF23", "None"),
        ("rr2", "ZF4", "ZF5", "ZF45", "None"),
        ("rr3", "ZF6", "ZF7", "ZF67", "None"),
        ("rr4", "ZF8", "ZF9", "ZF89", "None"),
        ("rr5", "ZF1", "ZF4", "ZF14", "None"),
        ("rr6", "ZF3", "ZF6", "ZF36", "None"),
        ("rr7", "ZF5", "ZF8", "ZF58", "None"),
    ],

    ("seed-73", "random-polymer"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "ZG6"),
        ("rr1", "ZG2", "ZG3", "ZG23", "ZG8"),
        ("rr2", "ZG4", "ZG5", "ZG45", "ZG0"),
        ("rr3", "ZG6", "ZG7", "ZG67", "ZG2"),
        ("rr4", "ZG8", "ZG9", "ZG89", "ZG4"),
        ("rr5", "ZG1", "ZG4", "ZG14", "ZG7"),
        ("rr6", "ZG3", "ZG6", "ZG36", "ZG9"),
        ("rr7", "ZG5", "ZG8", "ZG58", "ZG1"),
    ],
    ("seed-73", "shuffled-catalysts"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "ZG7"),
        ("rr1", "ZG2", "ZG3", "ZG23", "ZG9"),
        ("rr2", "ZG4", "ZG5", "ZG45", "ZG1"),
        ("rr3", "ZG6", "ZG7", "ZG67", "ZG3"),
        ("rr4", "ZG8", "ZG9", "ZG89", "ZG5"),
        ("rr5", "ZG1", "ZG4", "ZG14", "ZG8"),
        ("rr6", "ZG3", "ZG6", "ZG36", "ZG0"),
        ("rr7", "ZG5", "ZG8", "ZG58", "ZG2"),
    ],
    ("seed-73", "no-catalysis"): [
        ("rr0", "ZG0", "ZG1", "ZG01", "None"),
        ("rr1", "ZG2", "ZG3", "ZG23", "None"),
        ("rr2", "ZG4", "ZG5", "ZG45", "None"),
        ("rr3", "ZG6", "ZG7", "ZG67", "None"),
        ("rr4", "ZG8", "ZG9", "ZG89", "None"),
        ("rr5", "ZG1", "ZG4", "ZG14", "None"),
        ("rr6", "ZG3", "ZG6", "ZG36", "None"),
        ("rr7", "ZG5", "ZG8", "ZG58", "None"),
    ],
    ("seed-79", "random-polymer"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "ZH6"),
        ("rr1", "ZH2", "ZH3", "ZH23", "ZH8"),
        ("rr2", "ZH4", "ZH5", "ZH45", "ZH0"),
        ("rr3", "ZH6", "ZH7", "ZH67", "ZH2"),
        ("rr4", "ZH8", "ZH9", "ZH89", "ZH4"),
        ("rr5", "ZH1", "ZH4", "ZH14", "ZH7"),
        ("rr6", "ZH3", "ZH6", "ZH36", "ZH9"),
        ("rr7", "ZH5", "ZH8", "ZH58", "ZH1"),
    ],
    ("seed-79", "shuffled-catalysts"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "ZH7"),
        ("rr1", "ZH2", "ZH3", "ZH23", "ZH9"),
        ("rr2", "ZH4", "ZH5", "ZH45", "ZH1"),
        ("rr3", "ZH6", "ZH7", "ZH67", "ZH3"),
        ("rr4", "ZH8", "ZH9", "ZH89", "ZH5"),
        ("rr5", "ZH1", "ZH4", "ZH14", "ZH8"),
        ("rr6", "ZH3", "ZH6", "ZH36", "ZH0"),
        ("rr7", "ZH5", "ZH8", "ZH58", "ZH2"),
    ],
    ("seed-79", "no-catalysis"): [
        ("rr0", "ZH0", "ZH1", "ZH01", "None"),
        ("rr1", "ZH2", "ZH3", "ZH23", "None"),
        ("rr2", "ZH4", "ZH5", "ZH45", "None"),
        ("rr3", "ZH6", "ZH7", "ZH67", "None"),
        ("rr4", "ZH8", "ZH9", "ZH89", "None"),
        ("rr5", "ZH1", "ZH4", "ZH14", "None"),
        ("rr6", "ZH3", "ZH6", "ZH36", "None"),
        ("rr7", "ZH5", "ZH8", "ZH58", "None"),
    ],
    ("seed-83", "random-polymer"): [
        ("rr0", "ZI0", "ZI1", "ZI01", "ZI6"),
        ("rr1", "ZI2", "ZI3", "ZI23", "ZI8"),
        ("rr2", "ZI4", "ZI5", "ZI45", "ZI0"),
        ("rr3", "ZI6", "ZI7", "ZI67", "ZI2"),
        ("rr4", "ZI8", "ZI9", "ZI89", "ZI4"),
        ("rr5", "ZI1", "ZI4", "ZI14", "ZI7"),
        ("rr6", "ZI3", "ZI6", "ZI36", "ZI9"),
        ("rr7", "ZI5", "ZI8", "ZI58", "ZI1"),
    ],
    ("seed-83", "shuffled-catalysts"): [
        ("rr0", "ZI0", "ZI1", "ZI01", "ZI7"),
        ("rr1", "ZI2", "ZI3", "ZI23", "ZI9"),
        ("rr2", "ZI4", "ZI5", "ZI45", "ZI1"),
        ("rr3", "ZI6", "ZI7", "ZI67", "ZI3"),
        ("rr4", "ZI8", "ZI9", "ZI89", "ZI5"),
        ("rr5", "ZI1", "ZI4", "ZI14", "ZI8"),
        ("rr6", "ZI3", "ZI6", "ZI36", "ZI0"),
        ("rr7", "ZI5", "ZI8", "ZI58", "ZI2"),
    ],
    ("seed-83", "no-catalysis"): [
        ("rr0", "ZI0", "ZI1", "ZI01", "None"),
        ("rr1", "ZI2", "ZI3", "ZI23", "None"),
        ("rr2", "ZI4", "ZI5", "ZI45", "None"),
        ("rr3", "ZI6", "ZI7", "ZI67", "None"),
        ("rr4", "ZI8", "ZI9", "ZI89", "None"),
        ("rr5", "ZI1", "ZI4", "ZI14", "None"),
        ("rr6", "ZI3", "ZI6", "ZI36", "None"),
        ("rr7", "ZI5", "ZI8", "ZI58", "None"),
    ],
    ("seed-89", "random-polymer"): [
        ("rr0", "ZJ0", "ZJ1", "ZJ01", "ZJ6"),
        ("rr1", "ZJ2", "ZJ3", "ZJ23", "ZJ8"),
        ("rr2", "ZJ4", "ZJ5", "ZJ45", "ZJ0"),
        ("rr3", "ZJ6", "ZJ7", "ZJ67", "ZJ2"),
        ("rr4", "ZJ8", "ZJ9", "ZJ89", "ZJ4"),
        ("rr5", "ZJ1", "ZJ4", "ZJ14", "ZJ7"),
        ("rr6", "ZJ3", "ZJ6", "ZJ36", "ZJ9"),
        ("rr7", "ZJ5", "ZJ8", "ZJ58", "ZJ1"),
    ],
    ("seed-89", "shuffled-catalysts"): [
        ("rr0", "ZJ0", "ZJ1", "ZJ01", "ZJ7"),
        ("rr1", "ZJ2", "ZJ3", "ZJ23", "ZJ9"),
        ("rr2", "ZJ4", "ZJ5", "ZJ45", "ZJ1"),
        ("rr3", "ZJ6", "ZJ7", "ZJ67", "ZJ3"),
        ("rr4", "ZJ8", "ZJ9", "ZJ89", "ZJ5"),
        ("rr5", "ZJ1", "ZJ4", "ZJ14", "ZJ8"),
        ("rr6", "ZJ3", "ZJ6", "ZJ36", "ZJ0"),
        ("rr7", "ZJ5", "ZJ8", "ZJ58", "ZJ2"),
    ],
    ("seed-89", "no-catalysis"): [
        ("rr0", "ZJ0", "ZJ1", "ZJ01", "None"),
        ("rr1", "ZJ2", "ZJ3", "ZJ23", "None"),
        ("rr2", "ZJ4", "ZJ5", "ZJ45", "None"),
        ("rr3", "ZJ6", "ZJ7", "ZJ67", "None"),
        ("rr4", "ZJ8", "ZJ9", "ZJ89", "None"),
        ("rr5", "ZJ1", "ZJ4", "ZJ14", "None"),
        ("rr6", "ZJ3", "ZJ6", "ZJ36", "None"),
        ("rr7", "ZJ5", "ZJ8", "ZJ58", "None"),
    ],
    ("seed-97", "random-polymer"): [
        ("rr0", "ZK0", "ZK1", "ZK01", "ZK6"),
        ("rr1", "ZK2", "ZK3", "ZK23", "ZK8"),
        ("rr2", "ZK4", "ZK5", "ZK45", "ZK0"),
        ("rr3", "ZK6", "ZK7", "ZK67", "ZK2"),
        ("rr4", "ZK8", "ZK9", "ZK89", "ZK4"),
        ("rr5", "ZK1", "ZK4", "ZK14", "ZK7"),
        ("rr6", "ZK3", "ZK6", "ZK36", "ZK9"),
        ("rr7", "ZK5", "ZK8", "ZK58", "ZK1"),
    ],
    ("seed-97", "shuffled-catalysts"): [
        ("rr0", "ZK0", "ZK1", "ZK01", "ZK7"),
        ("rr1", "ZK2", "ZK3", "ZK23", "ZK9"),
        ("rr2", "ZK4", "ZK5", "ZK45", "ZK1"),
        ("rr3", "ZK6", "ZK7", "ZK67", "ZK3"),
        ("rr4", "ZK8", "ZK9", "ZK89", "ZK5"),
        ("rr5", "ZK1", "ZK4", "ZK14", "ZK8"),
        ("rr6", "ZK3", "ZK6", "ZK36", "ZK0"),
        ("rr7", "ZK5", "ZK8", "ZK58", "ZK2"),
    ],
    ("seed-97", "no-catalysis"): [
        ("rr0", "ZK0", "ZK1", "ZK01", "None"),
        ("rr1", "ZK2", "ZK3", "ZK23", "None"),
        ("rr2", "ZK4", "ZK5", "ZK45", "None"),
        ("rr3", "ZK6", "ZK7", "ZK67", "None"),
        ("rr4", "ZK8", "ZK9", "ZK89", "None"),
        ("rr5", "ZK1", "ZK4", "ZK14", "None"),
        ("rr6", "ZK3", "ZK6", "ZK36", "None"),
        ("rr7", "ZK5", "ZK8", "ZK58", "None"),
    ],
    ("seed-101", "random-polymer"): [
        ("rr0", "ZL0", "ZL1", "ZL01", "ZL6"),
        ("rr1", "ZL2", "ZL3", "ZL23", "ZL8"),
        ("rr2", "ZL4", "ZL5", "ZL45", "ZL0"),
        ("rr3", "ZL6", "ZL7", "ZL67", "ZL2"),
        ("rr4", "ZL8", "ZL9", "ZL89", "ZL4"),
        ("rr5", "ZL1", "ZL4", "ZL14", "ZL7"),
        ("rr6", "ZL3", "ZL6", "ZL36", "ZL9"),
        ("rr7", "ZL5", "ZL8", "ZL58", "ZL1"),
    ],
    ("seed-101", "shuffled-catalysts"): [
        ("rr0", "ZL0", "ZL1", "ZL01", "ZL7"),
        ("rr1", "ZL2", "ZL3", "ZL23", "ZL9"),
        ("rr2", "ZL4", "ZL5", "ZL45", "ZL1"),
        ("rr3", "ZL6", "ZL7", "ZL67", "ZL3"),
        ("rr4", "ZL8", "ZL9", "ZL89", "ZL5"),
        ("rr5", "ZL1", "ZL4", "ZL14", "ZL8"),
        ("rr6", "ZL3", "ZL6", "ZL36", "ZL0"),
        ("rr7", "ZL5", "ZL8", "ZL58", "ZL2"),
    ],
    ("seed-101", "no-catalysis"): [
        ("rr0", "ZL0", "ZL1", "ZL01", "None"),
        ("rr1", "ZL2", "ZL3", "ZL23", "None"),
        ("rr2", "ZL4", "ZL5", "ZL45", "None"),
        ("rr3", "ZL6", "ZL7", "ZL67", "None"),
        ("rr4", "ZL8", "ZL9", "ZL89", "None"),
        ("rr5", "ZL1", "ZL4", "ZL14", "None"),
        ("rr6", "ZL3", "ZL6", "ZL36", "None"),
        ("rr7", "ZL5", "ZL8", "ZL58", "None"),
    ],
    ("seed-103", "random-polymer"): [
        ("rr0", "ZM0", "ZM1", "ZM01", "ZM6"),
        ("rr1", "ZM2", "ZM3", "ZM23", "ZM8"),
        ("rr2", "ZM4", "ZM5", "ZM45", "ZM0"),
        ("rr3", "ZM6", "ZM7", "ZM67", "ZM2"),
        ("rr4", "ZM8", "ZM9", "ZM89", "ZM4"),
        ("rr5", "ZM1", "ZM4", "ZM14", "ZM7"),
        ("rr6", "ZM3", "ZM6", "ZM36", "ZM9"),
        ("rr7", "ZM5", "ZM8", "ZM58", "ZM1"),
    ],
    ("seed-103", "shuffled-catalysts"): [
        ("rr0", "ZM0", "ZM1", "ZM01", "ZM7"),
        ("rr1", "ZM2", "ZM3", "ZM23", "ZM9"),
        ("rr2", "ZM4", "ZM5", "ZM45", "ZM1"),
        ("rr3", "ZM6", "ZM7", "ZM67", "ZM3"),
        ("rr4", "ZM8", "ZM9", "ZM89", "ZM5"),
        ("rr5", "ZM1", "ZM4", "ZM14", "ZM8"),
        ("rr6", "ZM3", "ZM6", "ZM36", "ZM0"),
        ("rr7", "ZM5", "ZM8", "ZM58", "ZM2"),
    ],
    ("seed-103", "no-catalysis"): [
        ("rr0", "ZM0", "ZM1", "ZM01", "None"),
        ("rr1", "ZM2", "ZM3", "ZM23", "None"),
        ("rr2", "ZM4", "ZM5", "ZM45", "None"),
        ("rr3", "ZM6", "ZM7", "ZM67", "None"),
        ("rr4", "ZM8", "ZM9", "ZM89", "None"),
        ("rr5", "ZM1", "ZM4", "ZM14", "None"),
        ("rr6", "ZM3", "ZM6", "ZM36", "None"),
        ("rr7", "ZM5", "ZM8", "ZM58", "None"),
    ],
    ("seed-107", "random-polymer"): [
        ("rr0", "ZN0", "ZN1", "ZN01", "ZN6"),
        ("rr1", "ZN2", "ZN3", "ZN23", "ZN8"),
        ("rr2", "ZN4", "ZN5", "ZN45", "ZN0"),
        ("rr3", "ZN6", "ZN7", "ZN67", "ZN2"),
        ("rr4", "ZN8", "ZN9", "ZN89", "ZN4"),
        ("rr5", "ZN1", "ZN4", "ZN14", "ZN7"),
        ("rr6", "ZN3", "ZN6", "ZN36", "ZN9"),
        ("rr7", "ZN5", "ZN8", "ZN58", "ZN1"),
    ],
    ("seed-107", "shuffled-catalysts"): [
        ("rr0", "ZN0", "ZN1", "ZN01", "ZN7"),
        ("rr1", "ZN2", "ZN3", "ZN23", "ZN9"),
        ("rr2", "ZN4", "ZN5", "ZN45", "ZN1"),
        ("rr3", "ZN6", "ZN7", "ZN67", "ZN3"),
        ("rr4", "ZN8", "ZN9", "ZN89", "ZN5"),
        ("rr5", "ZN1", "ZN4", "ZN14", "ZN8"),
        ("rr6", "ZN3", "ZN6", "ZN36", "ZN0"),
        ("rr7", "ZN5", "ZN8", "ZN58", "ZN2"),
    ],
    ("seed-107", "no-catalysis"): [
        ("rr0", "ZN0", "ZN1", "ZN01", "None"),
        ("rr1", "ZN2", "ZN3", "ZN23", "None"),
        ("rr2", "ZN4", "ZN5", "ZN45", "None"),
        ("rr3", "ZN6", "ZN7", "ZN67", "None"),
        ("rr4", "ZN8", "ZN9", "ZN89", "None"),
        ("rr5", "ZN1", "ZN4", "ZN14", "None"),
        ("rr6", "ZN3", "ZN6", "ZN36", "None"),
        ("rr7", "ZN5", "ZN8", "ZN58", "None"),
    ],
    ("seed-109", "random-polymer"): [
        ("rr0", "ZO0", "ZO1", "ZO01", "ZO6"),
        ("rr1", "ZO2", "ZO3", "ZO23", "ZO8"),
        ("rr2", "ZO4", "ZO5", "ZO45", "ZO0"),
        ("rr3", "ZO6", "ZO7", "ZO67", "ZO2"),
        ("rr4", "ZO8", "ZO9", "ZO89", "ZO4"),
        ("rr5", "ZO1", "ZO4", "ZO14", "ZO7"),
        ("rr6", "ZO3", "ZO6", "ZO36", "ZO9"),
        ("rr7", "ZO5", "ZO8", "ZO58", "ZO1"),
    ],
    ("seed-109", "shuffled-catalysts"): [
        ("rr0", "ZO0", "ZO1", "ZO01", "ZO7"),
        ("rr1", "ZO2", "ZO3", "ZO23", "ZO9"),
        ("rr2", "ZO4", "ZO5", "ZO45", "ZO1"),
        ("rr3", "ZO6", "ZO7", "ZO67", "ZO3"),
        ("rr4", "ZO8", "ZO9", "ZO89", "ZO5"),
        ("rr5", "ZO1", "ZO4", "ZO14", "ZO8"),
        ("rr6", "ZO3", "ZO6", "ZO36", "ZO0"),
        ("rr7", "ZO5", "ZO8", "ZO58", "ZO2"),
    ],
    ("seed-109", "no-catalysis"): [
        ("rr0", "ZO0", "ZO1", "ZO01", "None"),
        ("rr1", "ZO2", "ZO3", "ZO23", "None"),
        ("rr2", "ZO4", "ZO5", "ZO45", "None"),
        ("rr3", "ZO6", "ZO7", "ZO67", "None"),
        ("rr4", "ZO8", "ZO9", "ZO89", "None"),
        ("rr5", "ZO1", "ZO4", "ZO14", "None"),
        ("rr6", "ZO3", "ZO6", "ZO36", "None"),
        ("rr7", "ZO5", "ZO8", "ZO58", "None"),
    ],
    ("seed-113", "random-polymer"): [
        ("rr0", "ZP0", "ZP1", "ZP01", "ZP6"),
        ("rr1", "ZP2", "ZP3", "ZP23", "ZP8"),
        ("rr2", "ZP4", "ZP5", "ZP45", "ZP0"),
        ("rr3", "ZP6", "ZP7", "ZP67", "ZP2"),
        ("rr4", "ZP8", "ZP9", "ZP89", "ZP4"),
        ("rr5", "ZP1", "ZP4", "ZP14", "ZP7"),
        ("rr6", "ZP3", "ZP6", "ZP36", "ZP9"),
        ("rr7", "ZP5", "ZP8", "ZP58", "ZP1"),
    ],
    ("seed-113", "shuffled-catalysts"): [
        ("rr0", "ZP0", "ZP1", "ZP01", "ZP7"),
        ("rr1", "ZP2", "ZP3", "ZP23", "ZP9"),
        ("rr2", "ZP4", "ZP5", "ZP45", "ZP1"),
        ("rr3", "ZP6", "ZP7", "ZP67", "ZP3"),
        ("rr4", "ZP8", "ZP9", "ZP89", "ZP5"),
        ("rr5", "ZP1", "ZP4", "ZP14", "ZP8"),
        ("rr6", "ZP3", "ZP6", "ZP36", "ZP0"),
        ("rr7", "ZP5", "ZP8", "ZP58", "ZP2"),
    ],
    ("seed-113", "no-catalysis"): [
        ("rr0", "ZP0", "ZP1", "ZP01", "None"),
        ("rr1", "ZP2", "ZP3", "ZP23", "None"),
        ("rr2", "ZP4", "ZP5", "ZP45", "None"),
        ("rr3", "ZP6", "ZP7", "ZP67", "None"),
        ("rr4", "ZP8", "ZP9", "ZP89", "None"),
        ("rr5", "ZP1", "ZP4", "ZP14", "None"),
        ("rr6", "ZP3", "ZP6", "ZP36", "None"),
        ("rr7", "ZP5", "ZP8", "ZP58", "None"),
    ],

    ("seed-127", "random-polymer"): [
        ("rr0", "ZQ0", "ZQ1", "ZQ01", "ZQ6"),
        ("rr1", "ZQ2", "ZQ3", "ZQ23", "ZQ8"),
        ("rr2", "ZQ4", "ZQ5", "ZQ45", "ZQ0"),
        ("rr3", "ZQ6", "ZQ7", "ZQ67", "ZQ2"),
        ("rr4", "ZQ8", "ZQ9", "ZQ89", "ZQ4"),
        ("rr5", "ZQ1", "ZQ4", "ZQ14", "ZQ7"),
        ("rr6", "ZQ3", "ZQ6", "ZQ36", "ZQ9"),
        ("rr7", "ZQ5", "ZQ8", "ZQ58", "ZQ1"),
    ],
    ("seed-127", "shuffled-catalysts"): [
        ("rr0", "ZQ0", "ZQ1", "ZQ01", "ZQ7"),
        ("rr1", "ZQ2", "ZQ3", "ZQ23", "ZQ9"),
        ("rr2", "ZQ4", "ZQ5", "ZQ45", "ZQ1"),
        ("rr3", "ZQ6", "ZQ7", "ZQ67", "ZQ3"),
        ("rr4", "ZQ8", "ZQ9", "ZQ89", "ZQ5"),
        ("rr5", "ZQ1", "ZQ4", "ZQ14", "ZQ8"),
        ("rr6", "ZQ3", "ZQ6", "ZQ36", "ZQ0"),
        ("rr7", "ZQ5", "ZQ8", "ZQ58", "ZQ2"),
    ],
    ("seed-127", "no-catalysis"): [
        ("rr0", "ZQ0", "ZQ1", "ZQ01", "None"),
        ("rr1", "ZQ2", "ZQ3", "ZQ23", "None"),
        ("rr2", "ZQ4", "ZQ5", "ZQ45", "None"),
        ("rr3", "ZQ6", "ZQ7", "ZQ67", "None"),
        ("rr4", "ZQ8", "ZQ9", "ZQ89", "None"),
        ("rr5", "ZQ1", "ZQ4", "ZQ14", "None"),
        ("rr6", "ZQ3", "ZQ6", "ZQ36", "None"),
        ("rr7", "ZQ5", "ZQ8", "ZQ58", "None"),
    ],

    ("seed-131", "random-polymer"): [
        ("rr0", "ZR0", "ZR1", "ZR01", "ZR6"),
        ("rr1", "ZR2", "ZR3", "ZR23", "ZR8"),
        ("rr2", "ZR4", "ZR5", "ZR45", "ZR0"),
        ("rr3", "ZR6", "ZR7", "ZR67", "ZR2"),
        ("rr4", "ZR8", "ZR9", "ZR89", "ZR4"),
        ("rr5", "ZR1", "ZR4", "ZR14", "ZR7"),
        ("rr6", "ZR3", "ZR6", "ZR36", "ZR9"),
        ("rr7", "ZR5", "ZR8", "ZR58", "ZR1"),
    ],
    ("seed-131", "shuffled-catalysts"): [
        ("rr0", "ZR0", "ZR1", "ZR01", "ZR7"),
        ("rr1", "ZR2", "ZR3", "ZR23", "ZR9"),
        ("rr2", "ZR4", "ZR5", "ZR45", "ZR1"),
        ("rr3", "ZR6", "ZR7", "ZR67", "ZR3"),
        ("rr4", "ZR8", "ZR9", "ZR89", "ZR5"),
        ("rr5", "ZR1", "ZR4", "ZR14", "ZR8"),
        ("rr6", "ZR3", "ZR6", "ZR36", "ZR0"),
        ("rr7", "ZR5", "ZR8", "ZR58", "ZR2"),
    ],
    ("seed-131", "no-catalysis"): [
        ("rr0", "ZR0", "ZR1", "ZR01", "None"),
        ("rr1", "ZR2", "ZR3", "ZR23", "None"),
        ("rr2", "ZR4", "ZR5", "ZR45", "None"),
        ("rr3", "ZR6", "ZR7", "ZR67", "None"),
        ("rr4", "ZR8", "ZR9", "ZR89", "None"),
        ("rr5", "ZR1", "ZR4", "ZR14", "None"),
        ("rr6", "ZR3", "ZR6", "ZR36", "None"),
        ("rr7", "ZR5", "ZR8", "ZR58", "None"),
    ],
    ("seed-137", "random-polymer"): [
        ("rr0", "ZS0", "ZS1", "ZS01", "ZS6"),
        ("rr1", "ZS2", "ZS3", "ZS23", "ZS8"),
        ("rr2", "ZS4", "ZS5", "ZS45", "ZS0"),
        ("rr3", "ZS6", "ZS7", "ZS67", "ZS2"),
        ("rr4", "ZS8", "ZS9", "ZS89", "ZS4"),
        ("rr5", "ZS1", "ZS4", "ZS14", "ZS7"),
        ("rr6", "ZS3", "ZS6", "ZS36", "ZS9"),
        ("rr7", "ZS5", "ZS8", "ZS58", "ZS1"),
    ],
    ("seed-137", "shuffled-catalysts"): [
        ("rr0", "ZS0", "ZS1", "ZS01", "ZS7"),
        ("rr1", "ZS2", "ZS3", "ZS23", "ZS9"),
        ("rr2", "ZS4", "ZS5", "ZS45", "ZS1"),
        ("rr3", "ZS6", "ZS7", "ZS67", "ZS3"),
        ("rr4", "ZS8", "ZS9", "ZS89", "ZS5"),
        ("rr5", "ZS1", "ZS4", "ZS14", "ZS8"),
        ("rr6", "ZS3", "ZS6", "ZS36", "ZS0"),
        ("rr7", "ZS5", "ZS8", "ZS58", "ZS2"),
    ],
    ("seed-137", "no-catalysis"): [
        ("rr0", "ZS0", "ZS1", "ZS01", "None"),
        ("rr1", "ZS2", "ZS3", "ZS23", "None"),
        ("rr2", "ZS4", "ZS5", "ZS45", "None"),
        ("rr3", "ZS6", "ZS7", "ZS67", "None"),
        ("rr4", "ZS8", "ZS9", "ZS89", "None"),
        ("rr5", "ZS1", "ZS4", "ZS14", "None"),
        ("rr6", "ZS3", "ZS6", "ZS36", "None"),
        ("rr7", "ZS5", "ZS8", "ZS58", "None"),
    ],
    ("seed-139", "random-polymer"): [
        ("rr0", "ZT0", "ZT1", "ZT01", "ZT6"),
        ("rr1", "ZT2", "ZT3", "ZT23", "ZT8"),
        ("rr2", "ZT4", "ZT5", "ZT45", "ZT0"),
        ("rr3", "ZT6", "ZT7", "ZT67", "ZT2"),
        ("rr4", "ZT8", "ZT9", "ZT89", "ZT4"),
        ("rr5", "ZT1", "ZT4", "ZT14", "ZT7"),
        ("rr6", "ZT3", "ZT6", "ZT36", "ZT9"),
        ("rr7", "ZT5", "ZT8", "ZT58", "ZT1"),
    ],
    ("seed-139", "shuffled-catalysts"): [
        ("rr0", "ZT0", "ZT1", "ZT01", "ZT7"),
        ("rr1", "ZT2", "ZT3", "ZT23", "ZT9"),
        ("rr2", "ZT4", "ZT5", "ZT45", "ZT1"),
        ("rr3", "ZT6", "ZT7", "ZT67", "ZT3"),
        ("rr4", "ZT8", "ZT9", "ZT89", "ZT5"),
        ("rr5", "ZT1", "ZT4", "ZT14", "ZT8"),
        ("rr6", "ZT3", "ZT6", "ZT36", "ZT0"),
        ("rr7", "ZT5", "ZT8", "ZT58", "ZT2"),
    ],
    ("seed-139", "no-catalysis"): [
        ("rr0", "ZT0", "ZT1", "ZT01", "None"),
        ("rr1", "ZT2", "ZT3", "ZT23", "None"),
        ("rr2", "ZT4", "ZT5", "ZT45", "None"),
        ("rr3", "ZT6", "ZT7", "ZT67", "None"),
        ("rr4", "ZT8", "ZT9", "ZT89", "None"),
        ("rr5", "ZT1", "ZT4", "ZT14", "None"),
        ("rr6", "ZT3", "ZT6", "ZT36", "None"),
        ("rr7", "ZT5", "ZT8", "ZT58", "None"),
    ],
    ("seed-149", "random-polymer"): [
        ("rr0", "ZU0", "ZU1", "ZU01", "ZU6"),
        ("rr1", "ZU2", "ZU3", "ZU23", "ZU8"),
        ("rr2", "ZU4", "ZU5", "ZU45", "ZU0"),
        ("rr3", "ZU6", "ZU7", "ZU67", "ZU2"),
        ("rr4", "ZU8", "ZU9", "ZU89", "ZU4"),
        ("rr5", "ZU1", "ZU4", "ZU14", "ZU7"),
        ("rr6", "ZU3", "ZU6", "ZU36", "ZU9"),
        ("rr7", "ZU5", "ZU8", "ZU58", "ZU1"),
    ],
    ("seed-149", "shuffled-catalysts"): [
        ("rr0", "ZU0", "ZU1", "ZU01", "ZU7"),
        ("rr1", "ZU2", "ZU3", "ZU23", "ZU9"),
        ("rr2", "ZU4", "ZU5", "ZU45", "ZU1"),
        ("rr3", "ZU6", "ZU7", "ZU67", "ZU3"),
        ("rr4", "ZU8", "ZU9", "ZU89", "ZU5"),
        ("rr5", "ZU1", "ZU4", "ZU14", "ZU8"),
        ("rr6", "ZU3", "ZU6", "ZU36", "ZU0"),
        ("rr7", "ZU5", "ZU8", "ZU58", "ZU2"),
    ],
    ("seed-149", "no-catalysis"): [
        ("rr0", "ZU0", "ZU1", "ZU01", "None"),
        ("rr1", "ZU2", "ZU3", "ZU23", "None"),
        ("rr2", "ZU4", "ZU5", "ZU45", "None"),
        ("rr3", "ZU6", "ZU7", "ZU67", "None"),
        ("rr4", "ZU8", "ZU9", "ZU89", "None"),
        ("rr5", "ZU1", "ZU4", "ZU14", "None"),
        ("rr6", "ZU3", "ZU6", "ZU36", "None"),
        ("rr7", "ZU5", "ZU8", "ZU58", "None"),
    ],

    ("seed-151", "random-polymer"): [
        ("rr0", "ZV0", "ZV1", "ZV01", "ZV6"),
        ("rr1", "ZV2", "ZV3", "ZV23", "ZV8"),
        ("rr2", "ZV4", "ZV5", "ZV45", "ZV0"),
        ("rr3", "ZV6", "ZV7", "ZV67", "ZV2"),
        ("rr4", "ZV8", "ZV9", "ZV89", "ZV4"),
        ("rr5", "ZV1", "ZV4", "ZV14", "ZV7"),
        ("rr6", "ZV3", "ZV6", "ZV36", "ZV9"),
        ("rr7", "ZV5", "ZV8", "ZV58", "ZV1"),
    ],
    ("seed-151", "shuffled-catalysts"): [
        ("rr0", "ZV0", "ZV1", "ZV01", "ZV7"),
        ("rr1", "ZV2", "ZV3", "ZV23", "ZV9"),
        ("rr2", "ZV4", "ZV5", "ZV45", "ZV1"),
        ("rr3", "ZV6", "ZV7", "ZV67", "ZV3"),
        ("rr4", "ZV8", "ZV9", "ZV89", "ZV5"),
        ("rr5", "ZV1", "ZV4", "ZV14", "ZV8"),
        ("rr6", "ZV3", "ZV6", "ZV36", "ZV0"),
        ("rr7", "ZV5", "ZV8", "ZV58", "ZV2"),
    ],
    ("seed-151", "no-catalysis"): [
        ("rr0", "ZV0", "ZV1", "ZV01", "None"),
        ("rr1", "ZV2", "ZV3", "ZV23", "None"),
        ("rr2", "ZV4", "ZV5", "ZV45", "None"),
        ("rr3", "ZV6", "ZV7", "ZV67", "None"),
        ("rr4", "ZV8", "ZV9", "ZV89", "None"),
        ("rr5", "ZV1", "ZV4", "ZV14", "None"),
        ("rr6", "ZV3", "ZV6", "ZV36", "None"),
        ("rr7", "ZV5", "ZV8", "ZV58", "None"),
    ],
    ("seed-157", "random-polymer"): [
        ("rr0", "ZW0", "ZW1", "ZW01", "ZW6"),
        ("rr1", "ZW2", "ZW3", "ZW23", "ZW8"),
        ("rr2", "ZW4", "ZW5", "ZW45", "ZW0"),
        ("rr3", "ZW6", "ZW7", "ZW67", "ZW2"),
        ("rr4", "ZW8", "ZW9", "ZW89", "ZW4"),
        ("rr5", "ZW1", "ZW4", "ZW14", "ZW7"),
        ("rr6", "ZW3", "ZW6", "ZW36", "ZW9"),
        ("rr7", "ZW5", "ZW8", "ZW58", "ZW1"),
    ],
    ("seed-157", "shuffled-catalysts"): [
        ("rr0", "ZW0", "ZW1", "ZW01", "ZW7"),
        ("rr1", "ZW2", "ZW3", "ZW23", "ZW9"),
        ("rr2", "ZW4", "ZW5", "ZW45", "ZW1"),
        ("rr3", "ZW6", "ZW7", "ZW67", "ZW3"),
        ("rr4", "ZW8", "ZW9", "ZW89", "ZW5"),
        ("rr5", "ZW1", "ZW4", "ZW14", "ZW8"),
        ("rr6", "ZW3", "ZW6", "ZW36", "ZW0"),
        ("rr7", "ZW5", "ZW8", "ZW58", "ZW2"),
    ],
    ("seed-157", "no-catalysis"): [
        ("rr0", "ZW0", "ZW1", "ZW01", "None"),
        ("rr1", "ZW2", "ZW3", "ZW23", "None"),
        ("rr2", "ZW4", "ZW5", "ZW45", "None"),
        ("rr3", "ZW6", "ZW7", "ZW67", "None"),
        ("rr4", "ZW8", "ZW9", "ZW89", "None"),
        ("rr5", "ZW1", "ZW4", "ZW14", "None"),
        ("rr6", "ZW3", "ZW6", "ZW36", "None"),
        ("rr7", "ZW5", "ZW8", "ZW58", "None"),
    ],
    ("seed-163", "random-polymer"): [
        ("rr0", "ZX0", "ZX1", "ZX01", "ZX6"),
        ("rr1", "ZX2", "ZX3", "ZX23", "ZX8"),
        ("rr2", "ZX4", "ZX5", "ZX45", "ZX0"),
        ("rr3", "ZX6", "ZX7", "ZX67", "ZX2"),
        ("rr4", "ZX8", "ZX9", "ZX89", "ZX4"),
        ("rr5", "ZX1", "ZX4", "ZX14", "ZX7"),
        ("rr6", "ZX3", "ZX6", "ZX36", "ZX9"),
        ("rr7", "ZX5", "ZX8", "ZX58", "ZX1"),
    ],
    ("seed-163", "shuffled-catalysts"): [
        ("rr0", "ZX0", "ZX1", "ZX01", "ZX7"),
        ("rr1", "ZX2", "ZX3", "ZX23", "ZX9"),
        ("rr2", "ZX4", "ZX5", "ZX45", "ZX1"),
        ("rr3", "ZX6", "ZX7", "ZX67", "ZX3"),
        ("rr4", "ZX8", "ZX9", "ZX89", "ZX5"),
        ("rr5", "ZX1", "ZX4", "ZX14", "ZX8"),
        ("rr6", "ZX3", "ZX6", "ZX36", "ZX0"),
        ("rr7", "ZX5", "ZX8", "ZX58", "ZX2"),
    ],
    ("seed-163", "no-catalysis"): [
        ("rr0", "ZX0", "ZX1", "ZX01", "None"),
        ("rr1", "ZX2", "ZX3", "ZX23", "None"),
        ("rr2", "ZX4", "ZX5", "ZX45", "None"),
        ("rr3", "ZX6", "ZX7", "ZX67", "None"),
        ("rr4", "ZX8", "ZX9", "ZX89", "None"),
        ("rr5", "ZX1", "ZX4", "ZX14", "None"),
        ("rr6", "ZX3", "ZX6", "ZX36", "None"),
        ("rr7", "ZX5", "ZX8", "ZX58", "None"),
    ],

}

ACTIVE_PAIRS = {
    ("seed-7", "random-polymer"): {(0, 1)},
    ("seed-11", "random-polymer"): {(0, 1), (2, 3)},
    ("seed-13", "random-polymer"): {(0, 1), (2, 3)},
    ("seed-17", "random-polymer"): {(0, 1), (2, 3)},
}

EVENTS = {
    ("seed-7", "random-polymer"): "(event 0 rr0 P0 P1 P01 P10)\n(event 1 rr1 P2 P3 P10 P01)\n",
}


@dataclass(frozen=True)
class RunSpec:
    key: str
    seed: str
    rule_count: int
    family: str
    run_id: str
    summary: str


def control_suffix(family: str) -> str:
    return {"random-polymer": "random", "shuffled-catalysts": "shuffled", "no-catalysis": "no-catalysis"}[family]


def count_word(count: int) -> str:
    return {1: "one", 2: "two"}.get(count, str(count))


def build_specs() -> list[RunSpec]:
    specs: list[RunSpec] = []
    for seed, count in [("seed-7", 4), ("seed-11", 6), ("seed-13", 8), ("seed-17", 8), ("seed-19", 8), ("seed-23", 8), ("seed-29", 8), ("seed-31", 8), ("seed-37", 8), ("seed-41", 8), ("seed-43", 8), ("seed-47", 8), ("seed-53", 8), ("seed-59", 8), ("seed-61", 8), ("seed-67", 8), ("seed-71", 8), ("seed-73", 8), ("seed-79", 8), ("seed-83", 8), ("seed-89", 8), ("seed-97", 8), ("seed-101", 8), ("seed-103", 8), ("seed-107", 8), ("seed-109", 8), ("seed-113", 8), ("seed-127", 8), ("seed-131", 8), ("seed-137", 8), ("seed-139", 8), ("seed-149", 8), ("seed-151", 8), ("seed-157", 8), ("seed-163", 8)]:
        for family in ["random-polymer", "shuffled-catalysts", "no-catalysis"]:
            suffix = control_suffix(family)
            if seed == "seed-7":
                run_id = f"exp02-small-{suffix}"
            else:
                run_id = f"exp02-{seed}-rules-{count}-{suffix}"
            active = len(ACTIVE_PAIRS.get((seed, family), set()))
            if family == "random-polymer":
                summary = f"{seed}-rules-{count}-random-has-{count_word(active)}-active-pairs"
            else:
                summary = f"{seed}-rules-{count}-{suffix}-control-has-zero-active-pairs"
            if seed == "seed-7" and family == "random-polymer":
                summary = "seed-7-random-has-one-active-pair"
            elif seed == "seed-7" and family == "shuffled-catalysts":
                summary = "shuffled-control-has-zero-active-pairs"
            elif seed == "seed-7" and family == "no-catalysis":
                summary = "no-catalysis-control-has-zero-active-pairs"
            specs.append(RunSpec(f"{seed}-{suffix}", seed, count, family, run_id, summary))
    return specs


def rule_atom(rule: tuple[str, str, str, str, str]) -> str:
    rid, a, b, product, catalyst = rule
    return f"(rule {rid} {a} {b} {product} {catalyst})"


def acs_atoms(seed: str, family: str) -> str:
    rules = RULES[(seed, family)]
    active_pairs = ACTIVE_PAIRS.get((seed, family), set())
    lines = []
    for i in range(len(rules)):
        for j in range(i + 1, len(rules)):
            status = "active" if (i, j) in active_pairs else "rejected"
            products = f"({rules[i][3]} {rules[j][3]})"
            catalysts = f"({rules[i][4]} {rules[j][4]})"
            lines.append(
                f"(acs-candidate pair-{i}-{j} ({rule_atom(rules[i])} {rule_atom(rules[j])}) {products} {catalysts} {status})"
            )
    return "\n".join(lines) + "\n"


def metric_atoms(spec: RunSpec) -> str:
    active = len(ACTIVE_PAIRS.get((spec.seed, spec.family), set()))
    body = (
        f"(metric active-acs-count {spec.run_id} {active})\n"
        f"(metric control-family {spec.run_id} {spec.family})\n"
        f"(metric rule-count {spec.run_id} {spec.rule_count})\n"
    )
    if spec.seed == "seed-17":
        body += f"(metric generation-seam {spec.run_id} seed-to-components)\n"
    if spec.seed in {"seed-19", "seed-23"}:
        body += f"(metric generation-seam {spec.run_id} seed-to-components)\n"
        body += f"(metric sweep-kind {spec.run_id} generated-unplanted-control)\n"
    if spec.seed in {"seed-29", "seed-31", "seed-37", "seed-41", "seed-43", "seed-47", "seed-53", "seed-59", "seed-61", "seed-67", "seed-71", "seed-73", "seed-79", "seed-83", "seed-89", "seed-97", "seed-101", "seed-103", "seed-107", "seed-109", "seed-113", "seed-127", "seed-131", "seed-137", "seed-139", "seed-149", "seed-151", "seed-157", "seed-163"}:
        body += f"(metric generation-seam {spec.run_id} factored-seed-template)\n"
        body += f"(metric sweep-kind {spec.run_id} generated-unplanted-control)\n"
    return body


def write_file(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(FILE_HEADER + (body if body else EMPTY), encoding="utf-8")


def write_run(output_root: Path, spec: RunSpec) -> None:
    run_dir = output_root / spec.run_id
    write_file(run_dir / "CONFIG.metta", f"(run-config {spec.run_id} exp02 ({spec.seed}) 1 (candidate-cap {spec.rule_count} 1) {spec.family})\n")
    write_file(run_dir / "MANIFEST.metta", f"(run-manifest {spec.run_id} config-hash-{spec.run_id} petta-local swi-9-3-36 scripts-run-exp02-sh 0)\n")
    write_file(run_dir / "EVENTS.metta", EVENTS.get((spec.seed, spec.family), ""))
    write_file(run_dir / "ABUNDANCES.metta", ABUNDANCES_BY_SEED[spec.seed])
    write_file(run_dir / "METRICS.metta", metric_atoms(spec))
    write_file(run_dir / "ACS.metta", acs_atoms(spec.seed, spec.family))
    write_file(run_dir / "ABLATIONS.metta", "")
    write_file(run_dir / "SUMMARY.metta", f"(run-summary {spec.run_id} passed {spec.summary} True)\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    args = parser.parse_args()

    specs = build_specs()
    for spec in specs:
        write_run(args.output_root, spec)

    print(f"wrote {len(specs)} exp02 run-contract directories under {args.output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
