#!/usr/bin/env python3
"""Run the thin exp06 bridge path-search harness and write artifact files.

This host script performs only path-search/bookkeeping. It queries the already
PeTTa-exposed exp06 intervention-cost rows, runs a small deterministic Dijkstra
search over those rows, and serializes CONFIG, NODE_EVALUATIONS, PATHS, and
SUMMARY sections. Chemistry dynamics, RAF/ACS status, and intervention evidence
remain in PeTTa atoms.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from heapq import heappop, heappush
from pathlib import Path
from typing import Iterator

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = Path(os.environ.get("WORKSPACE", "/home/openclaw/research-agent"))
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "artifacts" / "exp06_bridge_path_search"
FILE_HEADER = "; Generated by scripts/write_exp06_bridge_path_files.py from PeTTa exp06 rows.\n"
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

QUERY_ROWS = (
    ("catalyst-assignment", "none", "specific-template", "preferred"),
    ("catalyst-assignment", "none", "broad-template", "alternate"),
    ("basal-food-replenishment", "basal-0", "basal-4", "negative-control"),
    ("candidate-pool-cap", "unbounded-for-raf-report", "cap-2", "unevaluated"),
    ("catalysis-map-offset", "none", "shuffled-1", "negative-control"),
    ("catalysis-map-offset", "none", "shuffled-9", "offset-sensitive-control"),
)
TARGET_STATUSES = {"reaches-raf-positive-territory", "offset-sensitive-raf-like-control"}
STRICT_TARGET_STATUSES = {"reaches-raf-positive-territory"}

RUN_MD = """# exp06 bridge path-search artifacts

Generated by `scripts/write_exp06_bridge_path_files.sh` from PeTTa-side exp06
intervention rows. The Python harness only queries PeTTa rows, runs Dijkstra
bookkeeping over those rows, and writes report sections; it does not implement
chemistry dynamics, candidate selection, catalysis, abundance updates, or RAF/ACS
detection.

## Reproduce

```bash
scripts/write_exp06_bridge_path_files.sh
scripts/test_exp06_bridge_path_files.sh
```

## Files

- `CONFIG.metta`: source expressions and host-role boundary.
- `NODE_EVALUATIONS.metta`: PeTTa-queried intervention rows as search nodes.
- `PATHS.metta`: Dijkstra-selected path and alternates.
- `SUMMARY.metta`: concise result and caveats.
"""


@dataclass(frozen=True)
class Row:
    variable: str
    start: str
    end: str
    tag: str
    atom: list

    @property
    def cost(self) -> int:
        return int(field_after(self.atom, "cost"))

    @property
    def status(self) -> str:
        return str(field_after(self.atom, "status"))

    @property
    def maximal_raf(self) -> object:
        return field_after(self.atom, "maximal-raf")

    @property
    def core_size(self) -> object:
        return field_after(self.atom, "core-size")

    @property
    def node_id(self) -> str:
        return f"{self.variable}:{self.end}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--petta-runner", type=Path, default=Path(os.environ.get("PETTA_RUNNER", WORKSPACE / "projects" / "omegaclaw" / "repos" / "PeTTa" / "run.sh")))
    parser.add_argument("--swipl-prefix", type=Path, default=Path(os.environ.get("SWI_PREFIX", WORKSPACE / "projects" / "omegaclaw" / "local" / "swipl-9.3.36")))
    parser.add_argument("--no-run-md", action="store_true", help="do not write RUN.md provenance")
    return parser.parse_args()


def strip_ansi(text: str) -> str:
    return ANSI_RE.sub("", text)


def tokenize_sexpr(text: str) -> list[str]:
    return re.findall(r"\(|\)|[^\s()]+", text)


def parse_sexpr(text: str) -> list | str | int:
    tokens = tokenize_sexpr(text)
    value, pos = parse_tokens(tokens, 0)
    if pos != len(tokens):
        raise ValueError(f"trailing tokens in expression: {text}")
    return value


def parse_tokens(tokens: list[str], pos: int) -> tuple[list | str | int, int]:
    if tokens[pos] == "(":
        pos += 1
        items = []
        while pos < len(tokens) and tokens[pos] != ")":
            item, pos = parse_tokens(tokens, pos)
            items.append(item)
        if pos >= len(tokens):
            raise ValueError("unclosed list")
        return items, pos + 1
    token = tokens[pos]
    try:
        return int(token), pos + 1
    except ValueError:
        return token, pos + 1


def atom_to_text(value: object) -> str:
    if isinstance(value, list):
        return "(" + " ".join(atom_to_text(item) for item in value) + ")"
    return str(value)


def field_after(atom: list, field: str) -> object:
    for idx, value in enumerate(atom[:-1]):
        if value == field:
            return atom[idx + 1]
    raise KeyError(f"field {field!r} not found in {atom_to_text(atom)}")


def query_rows(runner: Path, swipl_prefix: Path) -> list[Row]:
    query_lines = [
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp00.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp04.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp05.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp06.metta'})",
    ]
    for variable, start, end, _tag in QUERY_ROWS:
        query_lines.append(f"!(exp06-intervention-cost-row {variable} {start} {end})")

    with tempfile.NamedTemporaryFile("w", suffix=".metta", delete=False) as handle:
        handle.write("\n".join(query_lines) + "\n")
        query_path = Path(handle.name)

    env = os.environ.copy()
    env["PATH"] = f"{swipl_prefix / 'bin'}:{env.get('PATH', '')}"
    env["SWI_HOME_DIR"] = str(swipl_prefix / "lib" / "swipl")
    lib_path = swipl_prefix / "lib" / "swipl" / "lib" / "x86_64-linux"
    env["LD_LIBRARY_PATH"] = f"{lib_path}:{env.get('LD_LIBRARY_PATH', '')}"

    try:
        completed = subprocess.run(
            ["sh", str(runner), str(query_path)],
            cwd=REPO_ROOT,
            env=env,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    finally:
        query_path.unlink(missing_ok=True)

    lines = [line.strip() for line in strip_ansi(completed.stdout).splitlines() if line.strip()]
    result_lines = lines[-len(QUERY_ROWS):]
    rows = []
    for (variable, start, end, tag), line in zip(QUERY_ROWS, result_lines):
        atom = parse_sexpr(line)
        if not isinstance(atom, list) or not atom or atom[0] != "intervention-cost-row":
            raise ValueError(f"unexpected PeTTa row for {variable}/{end}: {line}")
        rows.append(Row(variable=variable, start=start, end=end, tag=tag, atom=atom))
    return rows


def dijkstra(rows: list[Row]) -> tuple[Row, list[Row]]:
    by_node = {row.node_id: row for row in rows}
    heap: list[tuple[int, int, str, list[str]]] = []
    for order, row in enumerate(rows):
        heappush(heap, (row.cost, order, row.node_id, [row.node_id]))

    best: dict[str, int] = {}
    evaluated = []
    while heap:
        cost, _order, node, path = heappop(heap)
        if node in best and best[node] <= cost:
            continue
        best[node] = cost
        row = by_node[node]
        evaluated.append(row)
        if row.status in STRICT_TARGET_STATUSES:
            alternatives = [r for r in rows if r is not row and r.status in TARGET_STATUSES]
            return row, alternatives
    raise RuntimeError("no PeTTa-queried positive target row found")


def render_config(rows: list[Row]) -> str:
    source_exprs = "\n  ".join(
        f"(source-expression (exp06-intervention-cost-row {row.variable} {row.start} {row.end}))" for row in rows
    )
    return f"""(exp06-bridge-path-config
  run-id exp06-bridge-path-search-v0
  source exp06-bounded-cost-table
  search-algorithm dijkstra
  edge-source petta-queried-intervention-cost-rows
  target-class raf-positive-territory
  host-role path-search-bookkeeping-and-serialization-only
  chemistry-kernel petta-native
  emergence-claim none
  {source_exprs})
"""


def render_node_evaluations(rows: list[Row]) -> str:
    entries = []
    for row in rows:
        entries.append(
            f"(node-evaluation {row.node_id} cost {row.cost} status {row.status} "
            f"maximal-raf {atom_to_text(row.maximal_raf)} core-size {atom_to_text(row.core_size)} "
            f"source-row {atom_to_text(row.atom)})"
        )
    return "(exp06-node-evaluations\n  " + "\n  ".join(entries) + "\n)\n"


def render_paths(winner: Row, alternatives: list[Row]) -> str:
    alt_entries = "\n  ".join(
        f"(alternate-path cost {row.cost} node {row.node_id} status {row.status})" for row in alternatives
    )
    return f"""(exp06-dijkstra-paths
  (winning-path cost {winner.cost} nodes (initial {winner.node_id}) status {winner.status} source-row {atom_to_text(winner.atom)})
  {alt_entries}
)
"""


def render_summary(winner: Row, alternatives: list[Row], rows: list[Row]) -> str:
    positive_count = sum(1 for row in rows if row.status in TARGET_STATUSES)
    return f"""(exp06-bridge-path-summary
  result shortest-positive-path-found
  winning-variable {winner.variable}
  winning-change {winner.start}->{winner.end}
  winning-cost {winner.cost}
  positive-or-raf-like-rows {positive_count}
  evaluated-rows {len(rows)}
  caveat diagnostic-bridge-not-emergence-claim
  caveat terminal-fixture-is-engineered
  caveat offset-sensitive-raf-like-controls-are-not-unguided-emergence
  chemistry-kernel petta-native
  host-role path-search-bookkeeping-only
  emergence-claim none)
"""


def write_artifacts(output_root: Path, sections: dict[str, str], write_run_md: bool) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    for filename, body in sections.items():
        (output_root / filename).write_text(FILE_HEADER + body, encoding="utf-8")
    if write_run_md:
        (output_root / "RUN.md").write_text(RUN_MD, encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = query_rows(args.petta_runner, args.swipl_prefix)
    winner, alternatives = dijkstra(rows)
    sections = {
        "CONFIG.metta": render_config(rows),
        "NODE_EVALUATIONS.metta": render_node_evaluations(rows),
        "PATHS.metta": render_paths(winner, alternatives),
        "SUMMARY.metta": render_summary(winner, alternatives, rows),
    }
    write_artifacts(args.output_root, sections, write_run_md=not args.no_run_md)
    print(f"wrote exp06 bridge path-search artifacts to {args.output_root}")


if __name__ == "__main__":
    main()
