#!/usr/bin/env python3
"""Write exp03 productive-cap PeTTa run-file bundles to files.

This is a thin host harness: it asks PeTTa for the already-tested run-file
bundle sections and writes those section atoms to the v0.1 per-run file layout.
Chemistry, candidate selection, metrics, ACS candidates, and summaries remain in
PeTTa (`src/chem_dynamics.metta` + `src/run_contract.metta`).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = Path(os.environ.get("WORKSPACE", "/home/openclaw/research-agent"))
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "artifacts" / "exp03_productive_cap_files"
FILE_HEADER = "; Generated by scripts/write_exp03_productive_cap_files.py from PeTTa run-file bundles.\n"
FILE_NAMES = (
    "CONFIG.metta",
    "MANIFEST.metta",
    "EVENTS.metta",
    "ABUNDANCES.metta",
    "METRICS.metta",
    "ACS.metta",
    "ABLATIONS.metta",
    "SUMMARY.metta",
)
RUN_MD_HEADER = """# exp03 productive-cap file bundle artifacts

This directory is generated by `scripts/write_exp03_productive_cap_files.sh` from
PeTTa-side `run-file-bundle` atoms. Python only writes queried sections to disk;
chemistry, candidate selection, metrics, ACS candidates, ablations, and summaries
remain in PeTTa.

## Reproduce

```bash
scripts/write_exp03_productive_cap_files.sh
scripts/test_exp03_productive_cap_files.sh
```

## Bundles
"""
ACCESSORS = (
    "config",
    "manifest",
    "events",
    "abundances",
    "metrics",
    "acs",
    "ablations",
    "summary",
)
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


@dataclass(frozen=True)
class BundleQuery:
    name: str
    expr: str


BUNDLES = (
    BundleQuery(
        "exp03-cap5-productive-seed-13-random",
        "(exp03-cap5-productive-file-bundle seed-13 random-polymer)",
    ),
    BundleQuery(
        "exp03-cap6-rich-seed-11-random",
        "(exp03-cap6-rich-file-bundle seed-11 random)",
    ),
    BundleQuery(
        "exp03-cap6-productive-seed-11-random",
        "(exp03-cap6-productive-file-bundle seed-11 random)",
    ),
    BundleQuery(
        "exp03-cap6-productive-seed-13-random",
        "(exp03-cap6-productive-file-bundle seed-13 random-polymer)",
    ),
    BundleQuery(
        "exp03-cap6-productive-seed-17-random",
        "(exp03-cap6-productive-file-bundle seed-17 random-polymer)",
    ),
    BundleQuery(
        "exp03-cap7-productive-seed-13-random",
        "(exp03-cap7-productive-file-bundle seed-13 random-polymer)",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--petta-runner", type=Path, default=Path(os.environ.get("PETTA_RUNNER", WORKSPACE / "projects" / "omegaclaw" / "repos" / "PeTTa" / "run.sh")))
    parser.add_argument("--swipl-prefix", type=Path, default=Path(os.environ.get("SWI_PREFIX", WORKSPACE / "projects" / "omegaclaw" / "local" / "swipl-9.3.36")))
    parser.add_argument("--no-run-md", action="store_true", help="do not write the compact artifact RUN.md provenance file")
    return parser.parse_args()


def strip_ansi(text: str) -> str:
    return ANSI_RE.sub("", text)


def atom_from_run_file(line: str, expected_file: str) -> str:
    prefix = f"(run-file {expected_file} "
    if not line.startswith(prefix) or not line.endswith(")"):
        raise ValueError(f"expected {prefix!r} wrapper, got: {line}")
    return line[len(prefix):-1]


def query_bundle(bundle: BundleQuery, runner: Path, swipl_prefix: Path) -> dict[str, str]:
    query_lines = [
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp00.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp01.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'run_contract.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_exp02.metta'})",
        f"!(import! &self {REPO_ROOT / 'src' / 'chem_dynamics.metta'})",
        f"!(run-file-bundle-id {bundle.expr})",
    ]
    for accessor in ACCESSORS:
        query_lines.append(f"!(run-file-bundle-{accessor}-file {bundle.expr})")

    with tempfile.NamedTemporaryFile("w", suffix=".metta", delete=False) as handle:
        handle.write("\n".join(query_lines) + "\n")
        query_path = Path(handle.name)

    env = os.environ.copy()
    env["PATH"] = f"{swipl_prefix / 'bin'}:{env.get('PATH', '')}"
    env["SWI_HOME_DIR"] = str(swipl_prefix / "lib" / "swipl")
    lib_path = swipl_prefix / "lib" / "swipl" / "lib" / "x86_64-linux"
    env["LD_LIBRARY_PATH"] = f"{lib_path}:{env.get('LD_LIBRARY_PATH', '')}"

    try:
        completed = subprocess.run(
            ["sh", str(runner), str(query_path)],
            cwd=REPO_ROOT,
            env=env,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    finally:
        query_path.unlink(missing_ok=True)

    lines = [line.strip() for line in strip_ansi(completed.stdout).splitlines() if line.strip()]
    results = lines[-(1 + len(FILE_NAMES)):]
    run_id = results[0]
    if run_id != bundle.name:
        raise ValueError(f"bundle id mismatch: expected {bundle.name}, got {run_id}")

    return {
        filename: atom_from_run_file(line, filename)
        for filename, line in zip(FILE_NAMES, results[1:])
    }


def write_bundle(output_root: Path, bundle: BundleQuery, sections: dict[str, str]) -> None:
    run_dir = output_root / bundle.name
    run_dir.mkdir(parents=True, exist_ok=True)
    for filename in FILE_NAMES:
        content = sections[filename]
        (run_dir / filename).write_text(f"{FILE_HEADER}{content}\n", encoding="utf-8")


def write_run_md(output_root: Path) -> None:
    bundle_lines = []
    files = ", ".join(FILE_NAMES)
    for bundle in BUNDLES:
        bundle_lines.append(
            f"- `{bundle.name}` from `{bundle.expr}`; files: {files}."
        )
    content = RUN_MD_HEADER + "\n".join(bundle_lines) + "\n"
    (output_root / "RUN.md").write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)
    for bundle in BUNDLES:
        write_bundle(args.output_root, bundle, query_bundle(bundle, args.petta_runner, args.swipl_prefix))
    if not args.no_run_md:
        write_run_md(args.output_root)
    print(f"wrote {len(BUNDLES)} exp03 productive-cap run bundles to {args.output_root}")


if __name__ == "__main__":
    main()
